package lin

import (
	"github.com/whipstein/golinalg/golapack"
	"github.com/whipstein/golinalg/golapack/gltest"
	"github.com/whipstein/golinalg/mat"
)

// Drzt02 returns
//      || I - Q'*Q || / ( M * eps)
// where the matrix Q is defined by the Householder transformations
// generated by DTZRZF.
func Drzt02(m, n *int, af *mat.Matrix, lda *int, tau, work *mat.Vector, lwork *int) (drzt02Return float64) {
	var one, zero float64
	var i, info int

	rwork := vf(1)

	zero = 0.0
	one = 1.0

	drzt02Return = zero

	if (*lwork) < (*n)*(*n)+(*n) {
		gltest.Xerbla([]byte("DRZT02"), 7)
		return
	}

	//     Quick return if possible
	if (*m) <= 0 || (*n) <= 0 {
		return
	}

	//     Q := I
	golapack.Dlaset('F', n, n, &zero, &one, work.Matrix(*n, opts), n)

	//     Q := P(1) * ... * P(m) * Q
	golapack.Dormrz('L', 'N', n, n, m, toPtr((*n)-(*m)), af, lda, tau, work.Matrix(*n, opts), n, work.Off((*n)*(*n)+1-1), toPtr((*lwork)-(*n)*(*n)), &info)

	//     Q := P(m) * ... * P(1) * Q
	golapack.Dormrz('L', 'T', n, n, m, toPtr((*n)-(*m)), af, lda, tau, work.Matrix(*n, opts), n, work.Off((*n)*(*n)+1-1), toPtr((*lwork)-(*n)*(*n)), &info)

	//     Q := Q - I
	for i = 1; i <= (*n); i++ {
		work.Set((i-1)*(*n)+i-1, work.Get((i-1)*(*n)+i-1)-one)
	}

	drzt02Return = golapack.Dlange('O', n, n, work.Matrix(*n, opts), n, rwork) / (golapack.Dlamch(Epsilon) * float64(maxint(*m, *n)))
	return
}
