package eig

import (
	"fmt"
	"testing"

	"github.com/whipstein/golinalg/golapack"
	"github.com/whipstein/golinalg/golapack/gltest"
)

// derrst tests the error exits for Dsytrd, Dorgtr, Dormtr, Dsptrd,
// Dopgtr, Dopmtr, Dsteqr, Dsterf, Dstebz, Dstein, Dpteqr, Dsbtrd,
// Dsyev, Dsyevx, Dsyevd, Dsbev, Dsbevx, Dsbevd,
// Dspev, Dspevx, Dspevd, Dstev, Dstevx, Dstevd, and Dstedc.
// Dsyevd2stage, Dsyevr2stage, Dsyevx2stage,
// Dsyev2stage, Dsbev2stage, Dsbevd2stage,
// Dsbevx2stage, Dsytrd2stage, DsytrdSy2sb,
// DsytrdSb2st
func derrst(path string, t *testing.T) {
	var i, j, liw, lw, n, nmax, nt int
	var err error

	//     NMAX has to be at least 3 or LIW may be too small
	nmax = 3
	liw = 12 * nmax
	lw = 20 * nmax
	d := vf(3)
	e := vf(3)
	r := vf(3)
	tau := vf(3)
	w := vf(lw)
	x := vf(3)
	i1 := make([]int, 3)
	i2 := make([]int, 3)
	i3 := make([]int, 3)
	iw := make([]int, liw)
	a := mf(3, 3, opts)
	c := mf(3, 3, opts)
	q := mf(3, 3, opts)
	z := mf(3, 3, opts)

	errt := &gltest.Common.Infoc.Errt
	ok := &gltest.Common.Infoc.Ok
	srnamt := &gltest.Common.Srnamc.Srnamt

	c2 := path[1:3]

	//     Set the variables to innocuous values.
	for j = 1; j <= nmax; j++ {
		for i = 1; i <= nmax; i++ {
			a.Set(i-1, j-1, 1./float64(i+j))
		}
	}
	for j = 1; j <= nmax; j++ {
		d.Set(j-1, float64(j))
		e.Set(j-1, 0.0)
		i1[j-1] = j
		i2[j-1] = j
		tau.Set(j-1, 1.)
	}
	*ok = true
	nt = 0

	//     Test error exits for the st path.
	if c2 == "st" {
		//        Dsytrd
		*srnamt = "Dsytrd"
		*errt = fmt.Errorf("!upper && uplo != Lower: uplo=Unrecognized: /")
		err = golapack.Dsytrd('/', 0, a.Off(0, 0).UpdateRows(1), d, e, tau, w, 1)
		chkxer2("Dsytrd", err)
		*errt = fmt.Errorf("n < 0: n=-1")
		err = golapack.Dsytrd(Upper, -1, a.Off(0, 0).UpdateRows(1), d, e, tau, w, 1)
		chkxer2("Dsytrd", err)
		*errt = fmt.Errorf("a.Rows < max(1, n): a.Rows=1, n=2")
		err = golapack.Dsytrd(Upper, 2, a.Off(0, 0).UpdateRows(1), d, e, tau, w, 1)
		chkxer2("Dsytrd", err)
		*errt = fmt.Errorf("lwork < 1 && !lquery: lwork=0, lquery=false")
		err = golapack.Dsytrd(Upper, 0, a.Off(0, 0).UpdateRows(1), d, e, tau, w, 0)
		chkxer2("Dsytrd", err)
		nt = nt + 4

		//        Dsytrd2stage
		*srnamt = "Dsytrd2stage"
		*errt = fmt.Errorf("vect != 'N': vect='/'")
		err = golapack.Dsytrd2stage('/', Upper, 0, a.Off(0, 0).UpdateRows(1), d, e, tau, d, 1, w, 1)
		chkxer2("Dsytrd2stage", err)
		*errt = fmt.Errorf("vect != 'N': vect='H'")
		err = golapack.Dsytrd2stage('H', Upper, 0, a.Off(0, 0).UpdateRows(1), d, e, tau, d, 1, w, 1)
		chkxer2("Dsytrd2stage", err)
		*errt = fmt.Errorf("!upper && uplo != Lower: uplo=Unrecognized: /")
		err = golapack.Dsytrd2stage('N', '/', 0, a.Off(0, 0).UpdateRows(1), d, e, tau, d, 1, w, 1)
		chkxer2("Dsytrd2stage", err)
		*errt = fmt.Errorf("n < 0: n=-1")
		err = golapack.Dsytrd2stage('N', Upper, -1, a.Off(0, 0).UpdateRows(1), d, e, tau, d, 1, w, 1)
		chkxer2("Dsytrd2stage", err)
		*errt = fmt.Errorf("a.Rows < max(1, n): a.Rows=1, n=2")
		err = golapack.Dsytrd2stage('N', Upper, 2, a.Off(0, 0).UpdateRows(1), d, e, tau, d, 1, w, 1)
		chkxer2("Dsytrd2stage", err)
		*errt = fmt.Errorf("lhous2 < lhmin && !lquery: lhous2=0, lhmin=1, lquery=false")
		err = golapack.Dsytrd2stage('N', Upper, 0, a.Off(0, 0).UpdateRows(1), d, e, tau, d, 0, w, 1)
		chkxer2("Dsytrd2stage", err)
		*errt = fmt.Errorf("lwork < lwmin && !lquery: lwork=0, lwmin=1, lquery=false")
		err = golapack.Dsytrd2stage('N', Upper, 0, a.Off(0, 0).UpdateRows(1), d, e, tau, d, 1, w, 0)
		chkxer2("Dsytrd2stage", err)
		nt = nt + 7

		//        DsytrdSy2sb
		*srnamt = "DsytrdSy2sb"
		*errt = fmt.Errorf("!upper && uplo != Lower: uplo=Unrecognized: /")
		err = golapack.DsytrdSy2sb('/', 0, 0, a.Off(0, 0).UpdateRows(1), c.Off(0, 0).UpdateRows(1), tau, w, 1)
		chkxer2("DsytrdSy2sb", err)
		*errt = fmt.Errorf("n < 0: n=-1")
		err = golapack.DsytrdSy2sb(Upper, -1, 0, a.Off(0, 0).UpdateRows(1), c.Off(0, 0).UpdateRows(1), tau, w, 1)
		chkxer2("DsytrdSy2sb", err)
		*errt = fmt.Errorf("kd < 0: kd=-1")
		err = golapack.DsytrdSy2sb(Upper, 0, -1, a.Off(0, 0).UpdateRows(1), c.Off(0, 0).UpdateRows(1), tau, w, 1)
		chkxer2("DsytrdSy2sb", err)
		*errt = fmt.Errorf("a.Rows < max(1, n): a.Rows=1, n=2")
		err = golapack.DsytrdSy2sb(Upper, 2, 0, a.Off(0, 0).UpdateRows(1), c.Off(0, 0).UpdateRows(1), tau, w, 1)
		chkxer2("DsytrdSy2sb", err)
		*errt = fmt.Errorf("ab.Rows < max(1, kd+1): ab.Rows=1, kd=2")
		err = golapack.DsytrdSy2sb(Upper, 0, 2, a.Off(0, 0).UpdateRows(1), c.Off(0, 0).UpdateRows(1), tau, w, 1)
		chkxer2("DsytrdSy2sb", err)
		*errt = fmt.Errorf("lwork < lwmin && !lquery: lwork=0, lwmin=1, lquery=false")
		err = golapack.DsytrdSy2sb(Upper, 0, 0, a.Off(0, 0).UpdateRows(1), c.Off(0, 0).UpdateRows(1), tau, w, 0)
		chkxer2("DsytrdSy2sb", err)
		nt = nt + 6

		//        DsytrdSb2st
		*srnamt = "DsytrdSb2st"
		*errt = fmt.Errorf("!afters1 && stage1 != 'N': stage1='/'")
		err = golapack.DsytrdSb2st('/', 'N', Upper, 0, 0, a.Off(0, 0).UpdateRows(1), d, e, r, 1, w, 1)
		chkxer2("DsytrdSb2st", err)
		*errt = fmt.Errorf("vect != 'N': vect='/'")
		err = golapack.DsytrdSb2st('Y', '/', Upper, 0, 0, a.Off(0, 0).UpdateRows(1), d, e, r, 1, w, 1)
		chkxer2("DsytrdSb2st", err)
		*errt = fmt.Errorf("vect != 'N': vect='H'")
		err = golapack.DsytrdSb2st('Y', 'H', Upper, 0, 0, a.Off(0, 0).UpdateRows(1), d, e, r, 1, w, 1)
		chkxer2("DsytrdSb2st", err)
		*errt = fmt.Errorf("!upper && uplo != Lower: uplo=Unrecognized: /")
		err = golapack.DsytrdSb2st('Y', 'N', '/', 0, 0, a.Off(0, 0).UpdateRows(1), d, e, r, 1, w, 1)
		chkxer2("DsytrdSb2st", err)
		*errt = fmt.Errorf("n < 0: n=-1")
		err = golapack.DsytrdSb2st('Y', 'N', Upper, -1, 0, a.Off(0, 0).UpdateRows(1), d, e, r, 1, w, 1)
		chkxer2("DsytrdSb2st", err)
		*errt = fmt.Errorf("kd < 0: kd=-1")
		err = golapack.DsytrdSb2st('Y', 'N', Upper, 0, -1, a.Off(0, 0).UpdateRows(1), d, e, r, 1, w, 1)
		chkxer2("DsytrdSb2st", err)
		*errt = fmt.Errorf("ab.Rows < (kd + 1): ab.Rows=1, kd=1")
		err = golapack.DsytrdSb2st('Y', 'N', Upper, 0, 1, a.Off(0, 0).UpdateRows(1), d, e, r, 1, w, 1)
		chkxer2("DsytrdSb2st", err)
		*errt = fmt.Errorf("lhous < lhmin && !lquery: lhous=0, lhmin=1, lquery=false")
		err = golapack.DsytrdSb2st('Y', 'N', Upper, 0, 0, a.Off(0, 0).UpdateRows(1), d, e, r, 0, w, 1)
		chkxer2("DsytrdSb2st", err)
		*errt = fmt.Errorf("lwork < lwmin && !lquery: lwork=0, lwmin=1, lquery=false")
		err = golapack.DsytrdSb2st('Y', 'N', Upper, 0, 0, a.Off(0, 0).UpdateRows(1), d, e, r, 1, w, 0)
		chkxer2("DsytrdSb2st", err)
		nt = nt + 9

		//        Dorgtr
		*srnamt = "Dorgtr"
		*errt = fmt.Errorf("!upper && uplo != Lower: uplo=Unrecognized: /")
		err = golapack.Dorgtr('/', 0, a.Off(0, 0).UpdateRows(1), tau, w, 1)
		chkxer2("Dorgtr", err)
		*errt = fmt.Errorf("n < 0: n=-1")
		err = golapack.Dorgtr(Upper, -1, a.Off(0, 0).UpdateRows(1), tau, w, 1)
		chkxer2("Dorgtr", err)
		*errt = fmt.Errorf("a.Rows < max(1, n): a.Rows=1, n=2")
		err = golapack.Dorgtr(Upper, 2, a.Off(0, 0).UpdateRows(1), tau, w, 1)
		chkxer2("Dorgtr", err)
		*errt = fmt.Errorf("lwork < max(1, n-1) && !lquery: lwork=1, n=3, lquery=false")
		err = golapack.Dorgtr(Upper, 3, a.Off(0, 0).UpdateRows(3), tau, w, 1)
		chkxer2("Dorgtr", err)
		nt = nt + 4

		//        Dormtr
		*srnamt = "Dormtr"
		*errt = fmt.Errorf("!left && side != Right: side=Unrecognized: /")
		err = golapack.Dormtr('/', Upper, NoTrans, 0, 0, a.Off(0, 0).UpdateRows(1), tau, c.Off(0, 0).UpdateRows(1), w, 1)
		chkxer2("Dormtr", err)
		*errt = fmt.Errorf("!upper && uplo != Lower: uplo=Unrecognized: /")
		err = golapack.Dormtr(Left, '/', NoTrans, 0, 0, a.Off(0, 0).UpdateRows(1), tau, c.Off(0, 0).UpdateRows(1), w, 1)
		chkxer2("Dormtr", err)
		*errt = fmt.Errorf("trans != NoTrans && trans != Trans: trans=Unrecognized: /")
		err = golapack.Dormtr(Left, Upper, '/', 0, 0, a.Off(0, 0).UpdateRows(1), tau, c.Off(0, 0).UpdateRows(1), w, 1)
		chkxer2("Dormtr", err)
		*errt = fmt.Errorf("m < 0: m=-1")
		err = golapack.Dormtr(Left, Upper, NoTrans, -1, 0, a.Off(0, 0).UpdateRows(1), tau, c.Off(0, 0).UpdateRows(1), w, 1)
		chkxer2("Dormtr", err)
		*errt = fmt.Errorf("n < 0: n=-1")
		err = golapack.Dormtr(Left, Upper, NoTrans, 0, -1, a.Off(0, 0).UpdateRows(1), tau, c.Off(0, 0).UpdateRows(1), w, 1)
		chkxer2("Dormtr", err)
		*errt = fmt.Errorf("a.Rows < max(1, nq): a.Rows=1, nq=2")
		err = golapack.Dormtr(Left, Upper, NoTrans, 2, 0, a.Off(0, 0).UpdateRows(1), tau, c.Off(0, 0).UpdateRows(2), w, 1)
		chkxer2("Dormtr", err)
		*errt = fmt.Errorf("a.Rows < max(1, nq): a.Rows=1, nq=2")
		err = golapack.Dormtr(Right, Upper, NoTrans, 0, 2, a.Off(0, 0).UpdateRows(1), tau, c.Off(0, 0).UpdateRows(1), w, 1)
		chkxer2("Dormtr", err)
		*errt = fmt.Errorf("c.Rows < max(1, m): c.Rows=1, m=2")
		err = golapack.Dormtr(Left, Upper, NoTrans, 2, 0, a.Off(0, 0).UpdateRows(2), tau, c.Off(0, 0).UpdateRows(1), w, 1)
		chkxer2("Dormtr", err)
		*errt = fmt.Errorf("lwork < max(1, nw) && !lquery: lwork=1, nw=2, lquery=false")
		err = golapack.Dormtr(Left, Upper, NoTrans, 0, 2, a.Off(0, 0).UpdateRows(1), tau, c.Off(0, 0).UpdateRows(1), w, 1)
		chkxer2("Dormtr", err)
		*errt = fmt.Errorf("lwork < max(1, nw) && !lquery: lwork=1, nw=2, lquery=false")
		err = golapack.Dormtr(Right, Upper, NoTrans, 2, 0, a.Off(0, 0).UpdateRows(1), tau, c.Off(0, 0).UpdateRows(2), w, 1)
		chkxer2("Dormtr", err)
		nt = nt + 10

		//        Dsptrd
		*srnamt = "Dsptrd"
		*errt = fmt.Errorf("!upper && uplo != Lower: uplo=Unrecognized: /")
		err = golapack.Dsptrd('/', 0, r, d, e, tau)
		chkxer2("Dsptrd", err)
		*errt = fmt.Errorf("n < 0: n=-1")
		err = golapack.Dsptrd(Upper, -1, r, d, e, tau)
		chkxer2("Dsptrd", err)
		nt = nt + 2

		//        Dopgtr
		*srnamt = "Dopgtr"
		*errt = fmt.Errorf("!upper && uplo != Lower: uplo=Unrecognized: /")
		err = golapack.Dopgtr('/', 0, d, tau, z.Off(0, 0).UpdateRows(1), w)
		chkxer2("Dopgtr", err)
		*errt = fmt.Errorf("n < 0: n=-1")
		err = golapack.Dopgtr(Upper, -1, d, tau, z.Off(0, 0).UpdateRows(1), w)
		chkxer2("Dopgtr", err)
		*errt = fmt.Errorf("q.Rows < max(1, n): q.Rows=1, n=2")
		err = golapack.Dopgtr(Upper, 2, d, tau, z.Off(0, 0).UpdateRows(1), w)
		chkxer2("Dopgtr", err)
		nt = nt + 3

		//        Dopmtr
		*srnamt = "Dopmtr"
		*errt = fmt.Errorf("!left && side != Right: side=Unrecognized: /")
		err = golapack.Dopmtr('/', Upper, NoTrans, 0, 0, d, tau, c.Off(0, 0).UpdateRows(1), w)
		chkxer2("Dopmtr", err)
		*errt = fmt.Errorf("!upper && uplo != Lower: uplo=Unrecognized: /")
		err = golapack.Dopmtr(Left, '/', NoTrans, 0, 0, d, tau, c.Off(0, 0).UpdateRows(1), w)
		chkxer2("Dopmtr", err)
		*errt = fmt.Errorf("!notran && trans != Trans: trans=Unrecognized: /")
		err = golapack.Dopmtr(Left, Upper, '/', 0, 0, d, tau, c.Off(0, 0).UpdateRows(1), w)
		chkxer2("Dopmtr", err)
		*errt = fmt.Errorf("m < 0: m=-1")
		err = golapack.Dopmtr(Left, Upper, NoTrans, -1, 0, d, tau, c.Off(0, 0).UpdateRows(1), w)
		chkxer2("Dopmtr", err)
		*errt = fmt.Errorf("n < 0: n=-1")
		err = golapack.Dopmtr(Left, Upper, NoTrans, 0, -1, d, tau, c.Off(0, 0).UpdateRows(1), w)
		chkxer2("Dopmtr", err)
		*errt = fmt.Errorf("c.Rows < max(1, m): c.Rows=1, m=2")
		err = golapack.Dopmtr(Left, Upper, NoTrans, 2, 0, d, tau, c.Off(0, 0).UpdateRows(1), w)
		chkxer2("Dopmtr", err)
		nt = nt + 6

		//        Dpteqr
		*srnamt = "Dpteqr"
		*errt = fmt.Errorf("icompz < 0: compz='/'")
		_, err = golapack.Dpteqr('/', 0, d, e, z.Off(0, 0).UpdateRows(1), w)
		chkxer2("Dpteqr", err)
		*errt = fmt.Errorf("n < 0: n=-1")
		_, err = golapack.Dpteqr('N', -1, d, e, z.Off(0, 0).UpdateRows(1), w)
		chkxer2("Dpteqr", err)
		*errt = fmt.Errorf("(z.Rows < 1) || (icompz > 0 && z.Rows < max(1, n)): compz='V', z.Rows=1, n=2")
		_, err = golapack.Dpteqr('V', 2, d, e, z.Off(0, 0).UpdateRows(1), w)
		chkxer2("Dpteqr", err)
		nt = nt + 3

		//        Dstebz
		*srnamt = "Dstebz"
		*errt = fmt.Errorf("irange <= 0: _range='/'")
		_, _, _, err = golapack.Dstebz('/', 'E', 0, 0.0, 1.0, 1, 0, 0.0, d, e, x, &i1, &i2, w, &iw)
		chkxer2("Dstebz", err)
		*errt = fmt.Errorf("iorder <= 0: order='/'")
		_, _, _, err = golapack.Dstebz('A', '/', 0, 0.0, 0.0, 0, 0, 0.0, d, e, x, &i1, &i2, w, &iw)
		chkxer2("Dstebz", err)
		*errt = fmt.Errorf("n < 0: n=-1")
		_, _, _, err = golapack.Dstebz('A', 'E', -1, 0.0, 0.0, 0, 0, 0.0, d, e, x, &i1, &i2, w, &iw)
		chkxer2("Dstebz", err)
		*errt = fmt.Errorf("vl >= vu: vl=0, vu=0")
		_, _, _, err = golapack.Dstebz('V', 'E', 0, 0.0, 0.0, 0, 0, 0.0, d, e, x, &i1, &i2, w, &iw)
		chkxer2("Dstebz", err)
		*errt = fmt.Errorf("irange == 3 && (il < 1 || il > max(1, n)): _range='I', il=0, iu=0, n=0")
		_, _, _, err = golapack.Dstebz('I', 'E', 0, 0.0, 0.0, 0, 0, 0.0, d, e, x, &i1, &i2, w, &iw)
		chkxer2("Dstebz", err)
		*errt = fmt.Errorf("irange == 3 && (il < 1 || il > max(1, n)): _range='I', il=2, iu=1, n=1")
		_, _, _, err = golapack.Dstebz('I', 'E', 1, 0.0, 0.0, 2, 1, 0.0, d, e, x, &i1, &i2, w, &iw)
		chkxer2("Dstebz", err)
		*errt = fmt.Errorf("irange == 3 && (iu < min(n, il) || iu > n): _range='I', il=1, iu=0, n=1")
		_, _, _, err = golapack.Dstebz('I', 'E', 1, 0.0, 0.0, 1, 0, 0.0, d, e, x, &i1, &i2, w, &iw)
		chkxer2("Dstebz", err)
		*errt = fmt.Errorf("irange == 3 && (iu < min(n, il) || iu > n): _range='I', il=1, iu=2, n=1")
		_, _, _, err = golapack.Dstebz('I', 'E', 1, 0.0, 0.0, 1, 2, 0.0, d, e, x, &i1, &i2, w, &iw)
		chkxer2("Dstebz", err)
		nt = nt + 8

		//        Dstein
		*srnamt = "Dstein"
		// *errt = fmt.Errorf("iblock[j-1] == iblock[j-2] && w[j-1] < w[j-2]: iblock[j-1]=%v, iblock[j-2]=%v, w[j-1]=%v, w[j-2]=%v", (*iblock)[j-1], (*iblock)[j-2], w.Get(j-1), w.Get(j-2))
		*errt = fmt.Errorf("n < 0: n=-1")
		_, err = golapack.Dstein(-1, d, e, 0, x, &i1, &i2, z.Off(0, 0).UpdateRows(1), w, &iw, &i3)
		chkxer2("Dstein", err)
		*errt = fmt.Errorf("m < 0 || m > n: m=-1, n=0")
		_, err = golapack.Dstein(0, d, e, -1, x, &i1, &i2, z.Off(0, 0).UpdateRows(1), w, &iw, &i3)
		chkxer2("Dstein", err)
		*errt = fmt.Errorf("m < 0 || m > n: m=1, n=0")
		_, err = golapack.Dstein(0, d, e, 1, x, &i1, &i2, z.Off(0, 0).UpdateRows(1), w, &iw, &i3)
		chkxer2("Dstein", err)
		*errt = fmt.Errorf("z.Rows < max(1, n): z.Rows=1, n=2")
		// *errt = fmt.Errorf("iblock[j-1] < iblock[j-2]: iblock[j-1]=0, iblock[j-2]=0")
		_, err = golapack.Dstein(2, d, e, 0, x, &i1, &i2, z.Off(0, 0).UpdateRows(1), w, &iw, &i3)
		chkxer2("Dstein", err)
		nt = nt + 4

		//        Dsteqr
		*srnamt = "Dsteqr"
		*errt = fmt.Errorf("icompz < 0: compz='/'")
		_, err = golapack.Dsteqr('/', 0, d, e, z.Off(0, 0).UpdateRows(1), w)
		chkxer2("Dsteqr", err)
		*errt = fmt.Errorf("n < 0: n=-1")
		_, err = golapack.Dsteqr('N', -1, d, e, z.Off(0, 0).UpdateRows(1), w)
		chkxer2("Dsteqr", err)
		*errt = fmt.Errorf("(z.Rows < 1) || (icompz > 0 && z.Rows < max(1, n)): compz='V', z.Rows=1, n=2")
		_, err = golapack.Dsteqr('V', 2, d, e, z.Off(0, 0).UpdateRows(1), w)
		chkxer2("Dsteqr", err)
		nt = nt + 3

		//        Dsterf
		*srnamt = "Dsterf"
		*errt = fmt.Errorf("n < 0: n=-1")
		_, err = golapack.Dsterf(-1, d, e)
		chkxer2("Dsterf", err)
		nt = nt + 1

		//        Dstedc
		*srnamt = "Dstedc"
		*errt = fmt.Errorf("icompz < 0: compz='/'")
		_, err = golapack.Dstedc('/', 0, d, e, z.Off(0, 0).UpdateRows(1), w, 1, &iw, 1)
		chkxer2("Dstedc", err)
		*errt = fmt.Errorf("n < 0: n=-1")
		_, err = golapack.Dstedc('N', -1, d, e, z.Off(0, 0).UpdateRows(1), w, 1, &iw, 1)
		chkxer2("Dstedc", err)
		*errt = fmt.Errorf("(z.Rows < 1) || (icompz > 0 && z.Rows < max(1, n)): compz='V', z.Rows=1, n=2")
		_, err = golapack.Dstedc('V', 2, d, e, z.Off(0, 0).UpdateRows(1), w, 23, &iw, 28)
		chkxer2("Dstedc", err)
		*errt = fmt.Errorf("lwork < lwmin && !lquery: lwork=0, lwmin=1, lquery=false")
		_, err = golapack.Dstedc('N', 1, d, e, z.Off(0, 0).UpdateRows(1), w, 0, &iw, 1)
		chkxer2("Dstedc", err)
		*errt = fmt.Errorf("lwork < lwmin && !lquery: lwork=0, lwmin=2, lquery=false")
		_, err = golapack.Dstedc('I', 2, d, e, z.Off(0, 0).UpdateRows(2), w, 0, &iw, 12)
		chkxer2("Dstedc", err)
		*errt = fmt.Errorf("lwork < lwmin && !lquery: lwork=0, lwmin=2, lquery=false")
		_, err = golapack.Dstedc('V', 2, d, e, z.Off(0, 0).UpdateRows(2), w, 0, &iw, 28)
		chkxer2("Dstedc", err)
		*errt = fmt.Errorf("liwork < liwmin && !lquery: liwork=0, liwmin=1, lquery=false")
		_, err = golapack.Dstedc('N', 1, d, e, z.Off(0, 0).UpdateRows(1), w, 1, &iw, 0)
		chkxer2("Dstedc", err)
		*errt = fmt.Errorf("liwork < liwmin && !lquery: liwork=0, liwmin=1, lquery=false")
		_, err = golapack.Dstedc('I', 2, d, e, z.Off(0, 0).UpdateRows(2), w, 19, &iw, 0)
		chkxer2("Dstedc", err)
		*errt = fmt.Errorf("liwork < liwmin && !lquery: liwork=0, liwmin=1, lquery=false")
		_, err = golapack.Dstedc('V', 2, d, e, z.Off(0, 0).UpdateRows(2), w, 23, &iw, 0)
		chkxer2("Dstedc", err)
		nt = nt + 9

		//        Dstevd
		*srnamt = "Dstevd"
		*errt = fmt.Errorf("!(wantz || jobz == 'N'): jobz='/'")
		_, err = golapack.Dstevd('/', 0, d, e, z.Off(0, 0).UpdateRows(1), w, 1, &iw, 1)
		chkxer2("Dstevd", err)
		*errt = fmt.Errorf("n < 0: n=-1")
		_, err = golapack.Dstevd('N', -1, d, e, z.Off(0, 0).UpdateRows(1), w, 1, &iw, 1)
		chkxer2("Dstevd", err)
		*errt = fmt.Errorf("z.Rows < 1 || (wantz && z.Rows < n): jobz='V', z.Rows=1, n=2")
		_, err = golapack.Dstevd('V', 2, d, e, z.Off(0, 0).UpdateRows(1), w, 19, &iw, 12)
		chkxer2("Dstevd", err)
		*errt = fmt.Errorf("lwork < lwmin && !lquery: lwork=0, lwmin=1, lquery=false")
		_, err = golapack.Dstevd('N', 1, d, e, z.Off(0, 0).UpdateRows(1), w, 0, &iw, 1)
		chkxer2("Dstevd", err)
		*errt = fmt.Errorf("lwork < lwmin && !lquery: lwork=12, lwmin=13, lquery=false")
		_, err = golapack.Dstevd('V', 2, d, e, z.Off(0, 0).UpdateRows(2), w, 12, &iw, 12)
		chkxer2("Dstevd", err)
		*errt = fmt.Errorf("liwork < liwmin && !lquery: liwork=0, liwmin=1, lquery=false")
		_, err = golapack.Dstevd('N', 0, d, e, z.Off(0, 0).UpdateRows(1), w, 1, &iw, 0)
		chkxer2("Dstevd", err)
		*errt = fmt.Errorf("liwork < liwmin && !lquery: liwork=11, liwmin=13, lquery=false")
		_, err = golapack.Dstevd('V', 2, d, e, z.Off(0, 0).UpdateRows(2), w, 19, &iw, 11)
		chkxer2("Dstevd", err)
		nt = nt + 7

		//        Dstev
		*srnamt = "Dstev"
		*errt = fmt.Errorf("!(wantz || jobz == 'N'): joz='/'")
		_, err = golapack.Dstev('/', 0, d, e, z.Off(0, 0).UpdateRows(1), w)
		chkxer2("Dstev", err)
		*errt = fmt.Errorf("n < 0: n=-1")
		_, err = golapack.Dstev('N', -1, d, e, z.Off(0, 0).UpdateRows(1), w)
		chkxer2("Dstev", err)
		*errt = fmt.Errorf("z.Rows < 1 || (wantz && z.Rows < n): jobz='V', z.Rows=1, n=2")
		_, err = golapack.Dstev('V', 2, d, e, z.Off(0, 0).UpdateRows(1), w)
		chkxer2("Dstev", err)
		nt = nt + 3

		//        Dstevx
		*srnamt = "Dstevx"
		*errt = fmt.Errorf("!(wantz || jobz == 'N'): jobz='/'")
		_, _, err = golapack.Dstevx('/', 'A', 0, d, e, 0.0, 0.0, 0, 0, 0.0, x, z.Off(0, 0).UpdateRows(1), w, &iw, &i3)
		chkxer2("Dstevx", err)
		*errt = fmt.Errorf("!(alleig || valeig || indeig): _range='/'")
		_, _, err = golapack.Dstevx('N', '/', 0, d, e, 0.0, 1.0, 1, 0, 0.0, x, z.Off(0, 0).UpdateRows(1), w, &iw, &i3)
		chkxer2("Dstevx", err)
		*errt = fmt.Errorf("n < 0: n=-1")
		_, _, err = golapack.Dstevx('N', 'A', -1, d, e, 0.0, 0.0, 0, 0, 0.0, x, z.Off(0, 0).UpdateRows(1), w, &iw, &i3)
		chkxer2("Dstevx", err)
		*errt = fmt.Errorf("n > 0 && vu <= vl: n=1, vl=0, vu=0")
		_, _, err = golapack.Dstevx('N', 'V', 1, d, e, 0.0, 0.0, 0, 0, 0.0, x, z.Off(0, 0).UpdateRows(1), w, &iw, &i3)
		chkxer2("Dstevx", err)
		*errt = fmt.Errorf("il < 1 || il > max(1, n): n=1, il=0")
		_, _, err = golapack.Dstevx('N', 'I', 1, d, e, 0.0, 0.0, 0, 0, 0.0, x, z.Off(0, 0).UpdateRows(1), w, &iw, &i3)
		chkxer2("Dstevx", err)
		*errt = fmt.Errorf("il < 1 || il > max(1, n): n=1, il=2")
		_, _, err = golapack.Dstevx('N', 'I', 1, d, e, 0.0, 0.0, 2, 1, 0.0, x, z.Off(0, 0).UpdateRows(1), w, &iw, &i3)
		chkxer2("Dstevx", err)
		*errt = fmt.Errorf("iu < min(n, il) || iu > n: n=2, il=2, iu=1")
		_, _, err = golapack.Dstevx('N', 'I', 2, d, e, 0.0, 0.0, 2, 1, 0.0, x, z.Off(0, 0).UpdateRows(1), w, &iw, &i3)
		chkxer2("Dstevx", err)
		*errt = fmt.Errorf("iu < min(n, il) || iu > n: n=1, il=1, iu=2")
		_, _, err = golapack.Dstevx('N', 'I', 1, d, e, 0.0, 0.0, 1, 2, 0.0, x, z.Off(0, 0).UpdateRows(1), w, &iw, &i3)
		chkxer2("Dstevx", err)
		*errt = fmt.Errorf("z.Rows < 1 || (wantz && z.Rows < n): jobz='V', z.Rows=1, n=2")
		_, _, err = golapack.Dstevx('V', 'A', 2, d, e, 0.0, 0.0, 0, 0, 0.0, x, z.Off(0, 0).UpdateRows(1), w, &iw, &i3)
		chkxer2("Dstevx", err)
		nt = nt + 9

		//        Dstevr
		n = 1
		*srnamt = "Dstevr"
		_iw2n1 := iw[2*n:]
		*errt = fmt.Errorf("!(wantz || jobz == 'N'): jobz='/'")
		_, _, err = golapack.Dstevr('/', 'A', 0, d, e, 0.0, 0.0, 1, 1, 0.0, r, z.Off(0, 0).UpdateRows(1), &iw, x, 20*n, &_iw2n1, 10*n)
		chkxer2("Dstevr", err)
		*errt = fmt.Errorf("!(alleig || valeig || indeig): _range='/'")
		_, _, err = golapack.Dstevr('V', '/', 0, d, e, 0.0, 0.0, 1, 1, 0.0, r, z.Off(0, 0).UpdateRows(1), &iw, x, 20*n, &_iw2n1, 10*n)
		chkxer2("Dstevr", err)
		*errt = fmt.Errorf("n < 0: n=-1")
		_, _, err = golapack.Dstevr('V', 'A', -1, d, e, 0.0, 0.0, 1, 1, 0.0, r, z.Off(0, 0).UpdateRows(1), &iw, x, 20*n, &_iw2n1, 10*n)
		chkxer2("Dstevr", err)
		*errt = fmt.Errorf("n > 0 && vu <= vl: n=1, vl=0, vu=0")
		_, _, err = golapack.Dstevr('V', 'V', 1, d, e, 0.0, 0.0, 1, 1, 0.0, r, z.Off(0, 0).UpdateRows(1), &iw, x, 20*n, &_iw2n1, 10*n)
		chkxer2("Dstevr", err)
		*errt = fmt.Errorf("il < 1 || il > max(1, n): n=1, il=0")
		_, _, err = golapack.Dstevr('V', 'I', 1, d, e, 0.0, 0.0, 0, 1, 0.0, w, z.Off(0, 0).UpdateRows(1), &iw, x, 20*n, &_iw2n1, 10*n)
		chkxer2("Dstevr", err)
		*errt = fmt.Errorf("iu < min(n, il) || iu > n: n=2, il=2, iu=1")
		// *errt = fmt.Errorf("z.Rows < 1 || (wantz && z.Rows < n): jobz='V', z.Rows=1, n=2")
		n = 2
		_, _, err = golapack.Dstevr('V', 'I', 2, d, e, 0.0, 0.0, 2, 1, 0.0, w, z.Off(0, 0).UpdateRows(1), &iw, x, 20*n, &_iw2n1, 10*n)
		chkxer2("Dstevr", err)
		*errt = fmt.Errorf("iu < min(n, il) || iu > n: n=2, il=2, iu=1")
		n = 1
		// _, _, err = golapack.Dstevr('V', 'I', 1, d, e, 0.0, 0.0, 1, 1, 0.0, w, z.Off(0, 0).UpdateRows(0), &iw, x, 20*n, &_iw2n1, 10*n)
		chkxer2("Dstevr", err)
		*errt = fmt.Errorf("lwork < lwmin && !lquery: lwork=19, lwmin=20, lquery=false")
		// *errt = fmt.Errorf("liwork < liwmin && !lquery: liwork=10, liwmin=11, lquery=false")
		_, _, err = golapack.Dstevr('V', 'I', 1, d, e, 0.0, 0.0, 1, 1, 0.0, w, z.Off(0, 0).UpdateRows(1), &iw, x, 20*n-1, &_iw2n1, 10*n)
		chkxer2("Dstevr", err)
		*errt = fmt.Errorf("liwork < liwmin && !lquery: liwork=9, liwmin=10, lquery=false")
		_, _, err = golapack.Dstevr('V', 'I', 1, d, e, 0.0, 0.0, 1, 1, 0.0, w, z.Off(0, 0).UpdateRows(1), &iw, x, 20*n, &_iw2n1, 10*n-1)
		chkxer2("Dstevr", err)
		nt = nt + 9

		//        Dsyevd
		*srnamt = "Dsyevd"
		*errt = fmt.Errorf("!(wantz || jobz == 'N'): jobz='/'")
		_, err = golapack.Dsyevd('/', Upper, 0, a.Off(0, 0).UpdateRows(1), x, w, 1, &iw, 1)
		chkxer2("Dsyevd", err)
		*errt = fmt.Errorf("!(lower || uplo == Upper): uplo=Unrecognized: /")
		_, err = golapack.Dsyevd('N', '/', 0, a.Off(0, 0).UpdateRows(1), x, w, 1, &iw, 1)
		chkxer2("Dsyevd", err)
		*errt = fmt.Errorf("n < 0: n=-1")
		_, err = golapack.Dsyevd('N', Upper, -1, a.Off(0, 0).UpdateRows(1), x, w, 1, &iw, 1)
		chkxer2("Dsyevd", err)
		*errt = fmt.Errorf("a.Rows < max(1, n): a.Rows=1, n=2")
		_, err = golapack.Dsyevd('N', Upper, 2, a.Off(0, 0).UpdateRows(1), x, w, 3, &iw, 1)
		chkxer2("Dsyevd", err)
		*errt = fmt.Errorf("lwork < lwmin && !lquery: lwork=0, lwmin=1, lquery=false")
		_, err = golapack.Dsyevd('N', Upper, 1, a.Off(0, 0).UpdateRows(1), x, w, 0, &iw, 1)
		chkxer2("Dsyevd", err)
		*errt = fmt.Errorf("lwork < lwmin && !lquery: lwork=4, lwmin=5, lquery=false")
		_, err = golapack.Dsyevd('N', Upper, 2, a.Off(0, 0).UpdateRows(2), x, w, 4, &iw, 1)
		chkxer2("Dsyevd", err)
		*errt = fmt.Errorf("lwork < lwmin && !lquery: lwork=20, lwmin=21, lquery=false")
		_, err = golapack.Dsyevd('V', Upper, 2, a.Off(0, 0).UpdateRows(2), x, w, 20, &iw, 12)
		chkxer2("Dsyevd", err)
		*errt = fmt.Errorf("liwork < liwmin && !lquery: liwork=0, liwmin=1, lquery=false")
		_, err = golapack.Dsyevd('N', Upper, 1, a.Off(0, 0).UpdateRows(1), x, w, 1, &iw, 0)
		chkxer2("Dsyevd", err)
		*errt = fmt.Errorf("liwork < liwmin && !lquery: liwork=0, liwmin=1, lquery=false")
		_, err = golapack.Dsyevd('N', Upper, 2, a.Off(0, 0).UpdateRows(2), x, w, 5, &iw, 0)
		chkxer2("Dsyevd", err)
		*errt = fmt.Errorf("liwork < liwmin && !lquery: liwork=11, liwmin=13, lquery=false")
		_, err = golapack.Dsyevd('V', Upper, 2, a.Off(0, 0).UpdateRows(2), x, w, 27, &iw, 11)
		chkxer2("Dsyevd", err)
		nt = nt + 10

		//        Dsyevd2stage
		*srnamt = "Dsyevd2stage"
		*errt = fmt.Errorf("jobz != 'N': jobz='/'")
		_, err = golapack.Dsyevd2stage('/', Upper, 0, a.Off(0, 0).UpdateRows(1), x, w, 1, &iw, 1)
		chkxer2("Dsyevd2stage", err)
		*errt = fmt.Errorf("jobz != 'N': jobz='V'")
		_, err = golapack.Dsyevd2stage('V', Upper, 0, a.Off(0, 0).UpdateRows(1), x, w, 1, &iw, 1)
		chkxer2("Dsyevd2stage", err)
		*errt = fmt.Errorf("!(lower || uplo == Upper): uplo=Unrecognized: /")
		_, err = golapack.Dsyevd2stage('N', '/', 0, a.Off(0, 0).UpdateRows(1), x, w, 1, &iw, 1)
		chkxer2("Dsyevd2stage", err)
		*errt = fmt.Errorf("n < 0: n=-1")
		_, err = golapack.Dsyevd2stage('N', Upper, -1, a.Off(0, 0).UpdateRows(1), x, w, 1, &iw, 1)
		chkxer2("Dsyevd2stage", err)
		*errt = fmt.Errorf("a.Rows < max(1, n): a.Rows=1, n=2")
		_, err = golapack.Dsyevd2stage('N', Upper, 2, a.Off(0, 0).UpdateRows(1), x, w, 3, &iw, 1)
		chkxer2("Dsyevd2stage", err)
		*errt = fmt.Errorf("lwork < lwmin && !lquery: lwork=0, lwmin=1, lquery=false")
		_, err = golapack.Dsyevd2stage('N', Upper, 1, a.Off(0, 0).UpdateRows(1), x, w, 0, &iw, 1)
		chkxer2("Dsyevd2stage", err)
		*errt = fmt.Errorf("lwork < lwmin && !lquery: lwork=4, lwmin=14, lquery=false")
		_, err = golapack.Dsyevd2stage('N', Upper, 2, a.Off(0, 0).UpdateRows(2), x, w, 4, &iw, 1)
		chkxer2("Dsyevd2stage", err)
		*errt = fmt.Errorf("liwork < liwmin && !lquery: liwork=0, liwmin=1, lquery=false")
		_, err = golapack.Dsyevd2stage('N', Upper, 1, a.Off(0, 0).UpdateRows(1), x, w, 1, &iw, 0)
		chkxer2("Dsyevd2stage", err)
		*errt = fmt.Errorf("liwork < liwmin && !lquery: liwork=0, liwmin=1, lquery=false")
		_, err = golapack.Dsyevd2stage('N', Upper, 2, a.Off(0, 0).UpdateRows(2), x, w, 2500, &iw, 0)
		chkxer2("Dsyevd2stage", err)
		nt = nt + 9

		//        Dsyevr
		*srnamt = "Dsyevr"
		n = 1
		*errt = fmt.Errorf("!(wantz || jobz == 'N'): jobz='/'")
		_, _, err = golapack.Dsyevr('/', 'A', Upper, 0, a.Off(0, 0).UpdateRows(1), 0.0, 0.0, 1, 1, 0.0, r, z.Off(0, 0).UpdateRows(1), &iw, d, 26*n, &_iw2n1, 10*n)
		chkxer2("Dsyevr", err)
		*errt = fmt.Errorf("!(alleig || valeig || indeig): _range='/'")
		_, _, err = golapack.Dsyevr('V', '/', Upper, 0, a.Off(0, 0).UpdateRows(1), 0.0, 0.0, 1, 1, 0.0, r, z.Off(0, 0).UpdateRows(1), &iw, d, 26*n, &_iw2n1, 10*n)
		chkxer2("Dsyevr", err)
		*errt = fmt.Errorf("!(lower || uplo == Upper): uplo=Unrecognized: /")
		_, _, err = golapack.Dsyevr('V', 'A', '/', -1, a.Off(0, 0).UpdateRows(1), 0.0, 0.0, 1, 1, 0.0, r, z.Off(0, 0).UpdateRows(1), &iw, d, 26*n, &_iw2n1, 10*n)
		chkxer2("Dsyevr", err)
		*errt = fmt.Errorf("n < 0: n=-1")
		_, _, err = golapack.Dsyevr('V', 'A', Upper, -1, a.Off(0, 0).UpdateRows(1), 0.0, 0.0, 1, 1, 0.0, r, z.Off(0, 0).UpdateRows(1), &iw, d, 26*n, &_iw2n1, 10*n)
		chkxer2("Dsyevr", err)
		*errt = fmt.Errorf("a.Rows < max(1, n): a.Rows=1, n=2")
		_, _, err = golapack.Dsyevr('V', 'A', Upper, 2, a.Off(0, 0).UpdateRows(1), 0.0, 0.0, 1, 1, 0.0, r, z.Off(0, 0).UpdateRows(1), &iw, d, 26*n, &_iw2n1, 10*n)
		chkxer2("Dsyevr", err)
		*errt = fmt.Errorf("n > 0 && vu <= vl: n=1, vl=0, vu=0")
		_, _, err = golapack.Dsyevr('V', 'V', Upper, 1, a.Off(0, 0).UpdateRows(1), 0.0, 0.0, 1, 1, 0.0, r, z.Off(0, 0).UpdateRows(1), &iw, d, 26*n, &_iw2n1, 10*n)
		chkxer2("Dsyevr", err)
		*errt = fmt.Errorf("il < 1 || il > max(1, n): n=1, il=0")
		_, _, err = golapack.Dsyevr('V', 'I', Upper, 1, a.Off(0, 0).UpdateRows(1), 0.0, 0.0, 0, 1, 0.0, r, z.Off(0, 0).UpdateRows(1), &iw, d, 26*n, &_iw2n1, 10*n)
		chkxer2("Dsyevr", err)
		*errt = fmt.Errorf("iu < min(n, il) || iu > n: n=2, il=2, iu=1")
		_, _, err = golapack.Dsyevr('V', 'I', Upper, 2, a.Off(0, 0).UpdateRows(2), 0.0, 0.0, 2, 1, 0.0, r, z.Off(0, 0).UpdateRows(1), &iw, d, 26*n, &_iw2n1, 10*n)
		chkxer2("Dsyevr", err)
		*errt = fmt.Errorf("z.Rows < 1 || (wantz && z.Rows < n): jobz='V', z.Rows=1, n=2")
		_, _, err = golapack.Dsyevr('V', 'I', Upper, 2, a.Off(0, 0).UpdateRows(2), 0.0, 0.0, 1, 1, 0.0, r, z.Off(0, 0).UpdateRows(1), &iw, d, 26*n, &_iw2n1, 10*n)
		chkxer2("Dsyevr", err)
		*errt = fmt.Errorf("lwork < lwmin && !lquery: lwork=25, lwmin=26, lquery=false")
		_, _, err = golapack.Dsyevr('V', 'I', Upper, 1, a.Off(0, 0).UpdateRows(1), 0.0, 0.0, 1, 1, 0.0, r, z.Off(0, 0).UpdateRows(1), &iw, d, 26*n-1, &_iw2n1, 10*n)
		chkxer2("Dsyevr", err)
		*errt = fmt.Errorf("liwork < liwmin && !lquery: liwork=9, liwmin=10, lquery=false")
		_, _, err = golapack.Dsyevr('V', 'I', Upper, 1, a.Off(0, 0).UpdateRows(1), 0.0, 0.0, 1, 1, 0.0, r, z.Off(0, 0).UpdateRows(1), &iw, d, 26*n, &_iw2n1, 10*n-1)
		chkxer2("Dsyevr", err)
		nt = nt + 11

		//        Dsyevr2stage
		*srnamt = "Dsyevr2stage"
		n = 1
		*errt = fmt.Errorf("jobz != 'N': jobz='/'")
		_, _, err = golapack.Dsyevr2stage('/', 'A', Upper, 0, a.Off(0, 0).UpdateRows(1), 0.0, 0.0, 1, 1, 0.0, r, z.Off(0, 0).UpdateRows(1), &iw, d, 26*n, &_iw2n1, 10*n)
		chkxer2("Dsyevr2stage", err)
		*errt = fmt.Errorf("jobz != 'N': jobz='V'")
		_, _, err = golapack.Dsyevr2stage('V', 'A', Upper, 0, a.Off(0, 0).UpdateRows(1), 0.0, 0.0, 1, 1, 0.0, r, z.Off(0, 0).UpdateRows(1), &iw, d, 26*n, &_iw2n1, 10*n)
		chkxer2("Dsyevr2stage", err)
		*errt = fmt.Errorf("!(alleig || valeig || indeig): _range='/'")
		_, _, err = golapack.Dsyevr2stage('N', '/', Upper, 0, a.Off(0, 0).UpdateRows(1), 0.0, 0.0, 1, 1, 0.0, r, z.Off(0, 0).UpdateRows(1), &iw, d, 26*n, &_iw2n1, 10*n)
		chkxer2("Dsyevr2stage", err)
		*errt = fmt.Errorf("!(lower || uplo == Upper): uplo=Unrecognized: /")
		_, _, err = golapack.Dsyevr2stage('N', 'A', '/', -1, a.Off(0, 0).UpdateRows(1), 0.0, 0.0, 1, 1, 0.0, r, z.Off(0, 0).UpdateRows(1), &iw, d, 26*n, &_iw2n1, 10*n)
		chkxer2("Dsyevr2stage", err)
		*errt = fmt.Errorf("n < 0: n=-1")
		_, _, err = golapack.Dsyevr2stage('N', 'A', Upper, -1, a.Off(0, 0).UpdateRows(1), 0.0, 0.0, 1, 1, 0.0, r, z.Off(0, 0).UpdateRows(1), &iw, d, 26*n, &_iw2n1, 10*n)
		chkxer2("Dsyevr2stage", err)
		*errt = fmt.Errorf("a.Rows < max(1, n): a.Rows=1, n=2")
		_, _, err = golapack.Dsyevr2stage('N', 'A', Upper, 2, a.Off(0, 0).UpdateRows(1), 0.0, 0.0, 1, 1, 0.0, r, z.Off(0, 0).UpdateRows(1), &iw, d, 26*n, &_iw2n1, 10*n)
		chkxer2("Dsyevr2stage", err)
		*errt = fmt.Errorf("n > 0 && vu <= vl: n=1, vl=0, vu=0")
		_, _, err = golapack.Dsyevr2stage('N', 'V', Upper, 1, a.Off(0, 0).UpdateRows(1), 0.0, 0.0, 1, 1, 0.0, r, z.Off(0, 0).UpdateRows(1), &iw, d, 26*n, &_iw2n1, 10*n)
		chkxer2("Dsyevr2stage", err)
		*errt = fmt.Errorf("il < 1 || il > max(1, n): n=1, il=0")
		_, _, err = golapack.Dsyevr2stage('N', 'I', Upper, 1, a.Off(0, 0).UpdateRows(1), 0.0, 0.0, 0, 1, 0.0, r, z.Off(0, 0).UpdateRows(1), &iw, d, 26*n, &_iw2n1, 10*n)
		chkxer2("Dsyevr2stage", err)
		*errt = fmt.Errorf("iu < min(n, il) || iu > n: n=2, il=2, iu=1")
		_, _, err = golapack.Dsyevr2stage('N', 'I', Upper, 2, a.Off(0, 0).UpdateRows(2), 0.0, 0.0, 2, 1, 0.0, r, z.Off(0, 0).UpdateRows(1), &iw, d, 26*n, &_iw2n1, 10*n)
		chkxer2("Dsyevr2stage", err)
		// *errt = fmt.Errorf("z.Rows < 1 || (wantz && z.Rows < n): jobz='N', z.Rows=1, n=2")
		// _, _, err = golapack.Dsyevr2stage('N', 'I', Upper, 2, a.Off(0, 0).UpdateRows(2), 0.0, 0.0, 1, 1, 0.0, r, z.Off(0, 0).UpdateRows(1), &iw, d, 26*n, &_iw2n1, 10*n)
		// chkxer2("Dsyevr2stage", err)
		*errt = fmt.Errorf("lwork < lwmin && !lquery: lwork=0, lwmin=26, lquery=false")
		_, _, err = golapack.Dsyevr2stage('N', 'I', Upper, 1, a.Off(0, 0).UpdateRows(1), 0.0, 0.0, 1, 1, 0.0, r, z.Off(0, 0).UpdateRows(1), &iw, d, 0, &_iw2n1, 10*n)
		chkxer2("Dsyevr2stage", err)
		*errt = fmt.Errorf("liwork < liwmin && !lquery: liwork=0, liwmin=10, lquery=false")
		_, _, err = golapack.Dsyevr2stage('N', 'I', Upper, 1, a.Off(0, 0).UpdateRows(1), 0.0, 0.0, 1, 1, 0.0, r, z.Off(0, 0).UpdateRows(1), &iw, d, 2600*n, &_iw2n1, 0)
		chkxer2("Dsyevr2stage", err)
		nt = nt + 12

		//        Dsyev
		*srnamt = "Dsyev"
		*errt = fmt.Errorf("!(wantz || jobz == 'N'): jobz='/'")
		_, err = golapack.Dsyev('/', Upper, 0, a.Off(0, 0).UpdateRows(1), x, w, 1)
		chkxer2("Dsyev", err)
		*errt = fmt.Errorf("!(lower || uplo == Upper): uplo=Unrecognized: /")
		_, err = golapack.Dsyev('N', '/', 0, a.Off(0, 0).UpdateRows(1), x, w, 1)
		chkxer2("Dsyev", err)
		*errt = fmt.Errorf("n < 0: n=-1")
		_, err = golapack.Dsyev('N', Upper, -1, a.Off(0, 0).UpdateRows(1), x, w, 1)
		chkxer2("Dsyev", err)
		*errt = fmt.Errorf("a.Rows < max(1, n): a.Rows=1, n=2")
		_, err = golapack.Dsyev('N', Upper, 2, a.Off(0, 0).UpdateRows(1), x, w, 3)
		chkxer2("Dsyev", err)
		*errt = fmt.Errorf("lwork < max(1, 3*n-1) && !lquery: lwork=1, n=1, lquery=false")
		_, err = golapack.Dsyev('N', Upper, 1, a.Off(0, 0).UpdateRows(1), x, w, 1)
		chkxer2("Dsyev", err)
		nt = nt + 5

		//        Dsyev2stage
		*srnamt = "Dsyev2stage"
		*errt = fmt.Errorf("jobz != 'N': jobz='/'")
		_, err = golapack.Dsyev2stage('/', Upper, 0, a.Off(0, 0).UpdateRows(1), x, w, 1)
		chkxer2("Dsyev2stage", err)
		*errt = fmt.Errorf("jobz != 'N': jobz='V'")
		_, err = golapack.Dsyev2stage('V', Upper, 0, a.Off(0, 0).UpdateRows(1), x, w, 1)
		chkxer2("Dsyev2stage", err)
		*errt = fmt.Errorf("!(lower || uplo == Upper): uplo=Unrecognized: /")
		_, err = golapack.Dsyev2stage('N', '/', 0, a.Off(0, 0).UpdateRows(1), x, w, 1)
		chkxer2("Dsyev2stage", err)
		*errt = fmt.Errorf("n < 0: n=-1")
		_, err = golapack.Dsyev2stage('N', Upper, -1, a.Off(0, 0).UpdateRows(1), x, w, 1)
		chkxer2("Dsyev2stage", err)
		*errt = fmt.Errorf("a.Rows < max(1, n): a.Rows=1, n=2")
		_, err = golapack.Dsyev2stage('N', Upper, 2, a.Off(0, 0).UpdateRows(1), x, w, 3)
		chkxer2("Dsyev2stage", err)
		*errt = fmt.Errorf("lwork < lwmin && !lquery: lwork=1, lwmin=7, lquery=false")
		_, err = golapack.Dsyev2stage('N', Upper, 1, a.Off(0, 0).UpdateRows(1), x, w, 1)
		chkxer2("Dsyev2stage", err)
		nt = nt + 6

		//        Dsyevx
		*srnamt = "Dsyevx"
		*errt = fmt.Errorf("!(wantz || jobz == 'N'): jobz='/'")
		_, _, err = golapack.Dsyevx('/', 'A', Upper, 0, a.Off(0, 0).UpdateRows(1), 0.0, 0.0, 0, 0, 0.0, x, z.Off(0, 0).UpdateRows(1), w, 1, &iw, &i3)
		chkxer2("Dsyevx", err)
		*errt = fmt.Errorf("!(alleig || valeig || indeig): _range='/'")
		_, _, err = golapack.Dsyevx('N', '/', Upper, 0, a.Off(0, 0).UpdateRows(1), 0.0, 1.0, 1, 0, 0.0, x, z.Off(0, 0).UpdateRows(1), w, 1, &iw, &i3)
		chkxer2("Dsyevx", err)
		*errt = fmt.Errorf("!(lower || uplo == Upper): uplo=Unrecognized: /")
		_, _, err = golapack.Dsyevx('N', 'A', '/', 0, a.Off(0, 0).UpdateRows(1), 0.0, 0.0, 0, 0, 0.0, x, z.Off(0, 0).UpdateRows(1), w, 1, &iw, &i3)
		chkxer2("Dsyevx", err)
		*errt = fmt.Errorf("n < 0: n=-1")
		_, _, err = golapack.Dsyevx('N', 'A', Upper, -1, a.Off(0, 0).UpdateRows(1), 0.0, 0.0, 0, 0, 0.0, x, z.Off(0, 0).UpdateRows(1), w, 1, &iw, &i3)
		chkxer2("Dsyevx", err)
		*errt = fmt.Errorf("a.Rows < max(1, n): a.Rows=1, n=2")
		_, _, err = golapack.Dsyevx('N', 'A', Upper, 2, a.Off(0, 0).UpdateRows(1), 0.0, 0.0, 0, 0, 0.0, x, z.Off(0, 0).UpdateRows(1), w, 16, &iw, &i3)
		chkxer2("Dsyevx", err)
		*errt = fmt.Errorf("n > 0 && vu <= vl: n=1, vl=0, vu=0")
		_, _, err = golapack.Dsyevx('N', 'V', Upper, 1, a.Off(0, 0).UpdateRows(1), 0.0, 0.0, 0, 0, 0.0, x, z.Off(0, 0).UpdateRows(1), w, 8, &iw, &i3)
		chkxer2("Dsyevx", err)
		*errt = fmt.Errorf("il < 1 || il > max(1, n): n=1, il=0")
		_, _, err = golapack.Dsyevx('N', 'I', Upper, 1, a.Off(0, 0).UpdateRows(1), 0.0, 0.0, 0, 0, 0.0, x, z.Off(0, 0).UpdateRows(1), w, 8, &iw, &i3)
		chkxer2("Dsyevx", err)
		*errt = fmt.Errorf("il < 1 || il > max(1, n): n=1, il=2")
		_, _, err = golapack.Dsyevx('N', 'I', Upper, 1, a.Off(0, 0).UpdateRows(1), 0.0, 0.0, 2, 1, 0.0, x, z.Off(0, 0).UpdateRows(1), w, 8, &iw, &i3)
		chkxer2("Dsyevx", err)
		*errt = fmt.Errorf("iu < min(n, il) || iu > n: n=2, il=2, iu=1")
		_, _, err = golapack.Dsyevx('N', 'I', Upper, 2, a.Off(0, 0).UpdateRows(2), 0.0, 0.0, 2, 1, 0.0, x, z.Off(0, 0).UpdateRows(1), w, 16, &iw, &i3)
		chkxer2("Dsyevx", err)
		*errt = fmt.Errorf("iu < min(n, il) || iu > n: n=1, il=1, iu=2")
		_, _, err = golapack.Dsyevx('N', 'I', Upper, 1, a.Off(0, 0).UpdateRows(1), 0.0, 0.0, 1, 2, 0.0, x, z.Off(0, 0).UpdateRows(1), w, 8, &iw, &i3)
		chkxer2("Dsyevx", err)
		*errt = fmt.Errorf("z.Rows < 1 || (wantz && z.Rows < n): jobz='V', z.Rows=1, n=2")
		_, _, err = golapack.Dsyevx('V', 'A', Upper, 2, a.Off(0, 0).UpdateRows(2), 0.0, 0.0, 0, 0, 0.0, x, z.Off(0, 0).UpdateRows(1), w, 16, &iw, &i3)
		chkxer2("Dsyevx", err)
		*errt = fmt.Errorf("lwork < lwkmin && !lquery: lwork=0, lwkmin=1, lquery=false")
		_, _, err = golapack.Dsyevx('V', 'A', Upper, 1, a.Off(0, 0).UpdateRows(1), 0.0, 0.0, 0, 0, 0.0, x, z.Off(0, 0).UpdateRows(1), w, 0, &iw, &i3)
		chkxer2("Dsyevx", err)
		nt = nt + 12

		//        Dsyevx2stage
		*srnamt = "Dsyevx2stage"
		*errt = fmt.Errorf("jobz != 'N': jobz='/'")
		_, _, err = golapack.Dsyevx2stage('/', 'A', Upper, 0, a.Off(0, 0).UpdateRows(1), 0.0, 0.0, 0, 0, 0.0, x, z.Off(0, 0).UpdateRows(1), w, 1, &iw, &i3)
		chkxer2("Dsyevx2stage", err)
		*errt = fmt.Errorf("jobz != 'N': jobz='V'")
		_, _, err = golapack.Dsyevx2stage('V', 'A', Upper, 0, a.Off(0, 0).UpdateRows(1), 0.0, 0.0, 0, 0, 0.0, x, z.Off(0, 0).UpdateRows(1), w, 1, &iw, &i3)
		chkxer2("Dsyevx2stage", err)
		*errt = fmt.Errorf("!(alleig || valeig || indeig): _range='/'")
		_, _, err = golapack.Dsyevx2stage('N', '/', Upper, 0, a.Off(0, 0).UpdateRows(1), 0.0, 1.0, 1, 0, 0.0, x, z.Off(0, 0).UpdateRows(1), w, 1, &iw, &i3)
		chkxer2("Dsyevx2stage", err)
		*errt = fmt.Errorf("!(lower || uplo == Upper): uplo=Unrecognized: /")
		_, _, err = golapack.Dsyevx2stage('N', 'A', '/', 0, a.Off(0, 0).UpdateRows(1), 0.0, 0.0, 0, 0, 0.0, x, z.Off(0, 0).UpdateRows(1), w, 1, &iw, &i3)
		chkxer2("Dsyevx2stage", err)
		*errt = fmt.Errorf("n < 0: n=-1")
		_, _, err = golapack.Dsyevx2stage('N', 'A', Upper, -1, a.Off(0, 0).UpdateRows(1), 0.0, 0.0, 0, 0, 0.0, x, z.Off(0, 0).UpdateRows(1), w, 1, &iw, &i3)
		chkxer2("Dsyevx2stage", err)
		*errt = fmt.Errorf("a.Rows < max(1, n): a.Rows=1, n=2")
		_, _, err = golapack.Dsyevx2stage('N', 'A', Upper, 2, a.Off(0, 0).UpdateRows(1), 0.0, 0.0, 0, 0, 0.0, x, z.Off(0, 0).UpdateRows(1), w, 16, &iw, &i3)
		chkxer2("Dsyevx2stage", err)
		*errt = fmt.Errorf("n > 0 && vu <= vl: n=1, vl=0, vu=0")
		_, _, err = golapack.Dsyevx2stage('N', 'V', Upper, 1, a.Off(0, 0).UpdateRows(1), 0.0, 0.0, 0, 0, 0.0, x, z.Off(0, 0).UpdateRows(1), w, 8, &iw, &i3)
		chkxer2("Dsyevx2stage", err)
		*errt = fmt.Errorf("il < 1 || il > max(1, n): n=1, il=0")
		_, _, err = golapack.Dsyevx2stage('N', 'I', Upper, 1, a.Off(0, 0).UpdateRows(1), 0.0, 0.0, 0, 0, 0.0, x, z.Off(0, 0).UpdateRows(1), w, 8, &iw, &i3)
		chkxer2("Dsyevx2stage", err)
		*errt = fmt.Errorf("il < 1 || il > max(1, n): n=1, il=2")
		_, _, err = golapack.Dsyevx2stage('N', 'I', Upper, 1, a.Off(0, 0).UpdateRows(1), 0.0, 0.0, 2, 1, 0.0, x, z.Off(0, 0).UpdateRows(1), w, 8, &iw, &i3)
		chkxer2("Dsyevx2stage", err)
		*errt = fmt.Errorf("iu < min(n, il) || iu > n: n=2, il=2, iu=1")
		_, _, err = golapack.Dsyevx2stage('N', 'I', Upper, 2, a.Off(0, 0).UpdateRows(2), 0.0, 0.0, 2, 1, 0.0, x, z.Off(0, 0).UpdateRows(1), w, 16, &iw, &i3)
		chkxer2("Dsyevx2stage", err)
		*errt = fmt.Errorf("iu < min(n, il) || iu > n: n=1, il=1, iu=2")
		_, _, err = golapack.Dsyevx2stage('N', 'I', Upper, 1, a.Off(0, 0).UpdateRows(1), 0.0, 0.0, 1, 2, 0.0, x, z.Off(0, 0).UpdateRows(1), w, 8, &iw, &i3)
		chkxer2("Dsyevx2stage", err)
		// *errt = fmt.Errorf("z.Rows < 1 || (wantz && z.Rows < n): jobz='N', z.Rows=1, n=2")
		// _, _, err = golapack.Dsyevx2stage('N', 'A', Upper, 2, a.Off(0, 0).UpdateRows(2), 0.0, 0.0, 0, 0, 0.0, x, z.Off(0, 0).UpdateRows(1), w, 16, &iw, &i3)
		// chkxer2("Dsyevx2stage", err)
		*errt = fmt.Errorf("lwork < lwmin && !lquery: lwork=0, lwmin=1, lquery=false")
		_, _, err = golapack.Dsyevx2stage('N', 'A', Upper, 1, a.Off(0, 0).UpdateRows(1), 0.0, 0.0, 0, 0, 0.0, x, z.Off(0, 0).UpdateRows(1), w, 0, &iw, &i3)
		chkxer2("Dsyevx2stage", err)
		nt = nt + 13

		//        Dspevd
		*srnamt = "Dspevd"
		*errt = fmt.Errorf("!(wantz || jobz == 'N'): jobz='/'")
		_, err = golapack.Dspevd('/', Upper, 0, d, x, z.Off(0, 0).UpdateRows(1), w, 1, &iw, 1)
		chkxer2("Dspevd", err)
		*errt = fmt.Errorf("!(uplo == Upper || uplo == Lower): uplo=Unrecognized: /")
		_, err = golapack.Dspevd('N', '/', 0, d, x, z.Off(0, 0).UpdateRows(1), w, 1, &iw, 1)
		chkxer2("Dspevd", err)
		*errt = fmt.Errorf("n < 0: n=-1")
		_, err = golapack.Dspevd('N', Upper, -1, d, x, z.Off(0, 0).UpdateRows(1), w, 1, &iw, 1)
		chkxer2("Dspevd", err)
		*errt = fmt.Errorf("z.Rows < 1 || (wantz && z.Rows < n): jobz='V', z.Rows=1, n=2")
		_, err = golapack.Dspevd('V', Upper, 2, d, x, z.Off(0, 0).UpdateRows(1), w, 23, &iw, 12)
		chkxer2("Dspevd", err)
		*errt = fmt.Errorf("lwork < lwmin && !lquery: lwork=0, lwmin=1, lquery=false")
		_, err = golapack.Dspevd('N', Upper, 1, d, x, z.Off(0, 0).UpdateRows(1), w, 0, &iw, 1)
		chkxer2("Dspevd", err)
		*errt = fmt.Errorf("lwork < lwmin && !lquery: lwork=3, lwmin=4, lquery=false")
		_, err = golapack.Dspevd('N', Upper, 2, d, x, z.Off(0, 0).UpdateRows(1), w, 3, &iw, 1)
		chkxer2("Dspevd", err)
		*errt = fmt.Errorf("lwork < lwmin && !lquery: lwork=16, lwmin=17, lquery=false")
		_, err = golapack.Dspevd('V', Upper, 2, d, x, z.Off(0, 0).UpdateRows(2), w, 16, &iw, 12)
		chkxer2("Dspevd", err)
		*errt = fmt.Errorf("liwork < liwmin && !lquery: liwork=0, liwmin=1, lquery=false")
		_, err = golapack.Dspevd('N', Upper, 1, d, x, z.Off(0, 0).UpdateRows(1), w, 1, &iw, 0)
		chkxer2("Dspevd", err)
		*errt = fmt.Errorf("liwork < liwmin && !lquery: liwork=0, liwmin=1, lquery=false")
		_, err = golapack.Dspevd('N', Upper, 2, d, x, z.Off(0, 0).UpdateRows(1), w, 4, &iw, 0)
		chkxer2("Dspevd", err)
		*errt = fmt.Errorf("liwork < liwmin && !lquery: liwork=11, liwmin=13, lquery=false")
		_, err = golapack.Dspevd('V', Upper, 2, d, x, z.Off(0, 0).UpdateRows(2), w, 23, &iw, 11)
		chkxer2("Dspevd", err)
		nt = nt + 10

		//        Dspev
		*srnamt = "Dspev"
		*errt = fmt.Errorf("!(wantz || jobz == 'N'): jobz='/'")
		_, err = golapack.Dspev('/', Upper, 0, d, w, z.Off(0, 0).UpdateRows(1), x)
		chkxer2("Dspev", err)
		*errt = fmt.Errorf("!(uplo == Upper || uplo == Lower): uplo=Unrecognized: /")
		_, err = golapack.Dspev('N', '/', 0, d, w, z.Off(0, 0).UpdateRows(1), x)
		chkxer2("Dspev", err)
		*errt = fmt.Errorf("n < 0: n=-1")
		_, err = golapack.Dspev('N', Upper, -1, d, w, z.Off(0, 0).UpdateRows(1), x)
		chkxer2("Dspev", err)
		*errt = fmt.Errorf("z.Rows < 1 || (wantz && z.Rows < n): jobz='V', z.Rows=1, n=2")
		_, err = golapack.Dspev('V', Upper, 2, d, w, z.Off(0, 0).UpdateRows(1), x)
		chkxer2("Dspev", err)
		nt = nt + 4

		//        Dspevx
		*srnamt = "Dspevx"
		*errt = fmt.Errorf("!(wantz || jobz == 'N'): jobz='/'")
		_, _, err = golapack.Dspevx('/', 'A', Upper, 0, d, 0.0, 0.0, 0, 0, 0.0, x, z.Off(0, 0).UpdateRows(1), w, &iw, &i3)
		chkxer2("Dspevx", err)
		*errt = fmt.Errorf("!(alleig || valeig || indeig): _range='/'")
		_, _, err = golapack.Dspevx('N', '/', Upper, 0, d, 0.0, 0.0, 0, 0, 0.0, x, z.Off(0, 0).UpdateRows(1), w, &iw, &i3)
		chkxer2("Dspevx", err)
		*errt = fmt.Errorf("!(uplo == Lower || uplo == Upper): uplo=Unrecognized: /")
		_, _, err = golapack.Dspevx('N', 'A', '/', 0, d, 0.0, 0.0, 0, 0, 0.0, x, z.Off(0, 0).UpdateRows(1), w, &iw, &i3)
		chkxer2("Dspevx", err)
		*errt = fmt.Errorf("n < 0: n=-1")
		_, _, err = golapack.Dspevx('N', 'A', Upper, -1, d, 0.0, 0.0, 0, 0, 0.0, x, z.Off(0, 0).UpdateRows(1), w, &iw, &i3)
		chkxer2("Dspevx", err)
		*errt = fmt.Errorf("n > 0 && vu <= vl: n=1, vu=0, vl=0")
		_, _, err = golapack.Dspevx('N', 'V', Upper, 1, d, 0.0, 0.0, 0, 0, 0.0, x, z.Off(0, 0).UpdateRows(1), w, &iw, &i3)
		chkxer2("Dspevx", err)
		*errt = fmt.Errorf("il < 1 || il > max(1, n): il=0, n=1")
		_, _, err = golapack.Dspevx('N', 'I', Upper, 1, d, 0.0, 0.0, 0, 0, 0.0, x, z.Off(0, 0).UpdateRows(1), w, &iw, &i3)
		chkxer2("Dspevx", err)
		*errt = fmt.Errorf("il < 1 || il > max(1, n): il=2, n=1")
		_, _, err = golapack.Dspevx('N', 'I', Upper, 1, d, 0.0, 0.0, 2, 1, 0.0, x, z.Off(0, 0).UpdateRows(1), w, &iw, &i3)
		chkxer2("Dspevx", err)
		*errt = fmt.Errorf("iu < min(n, il) || iu > n: iu=1, il=2, n=2")
		_, _, err = golapack.Dspevx('N', 'I', Upper, 2, d, 0.0, 0.0, 2, 1, 0.0, x, z.Off(0, 0).UpdateRows(1), w, &iw, &i3)
		chkxer2("Dspevx", err)
		*errt = fmt.Errorf("iu < min(n, il) || iu > n: iu=2, il=1, n=1")
		_, _, err = golapack.Dspevx('N', 'I', Upper, 1, d, 0.0, 0.0, 1, 2, 0.0, x, z.Off(0, 0).UpdateRows(1), w, &iw, &i3)
		chkxer2("Dspevx", err)
		*errt = fmt.Errorf("z.Rows < 1 || (wantz && z.Rows < n): jobz='V', z.Rows=1, n=2")
		_, _, err = golapack.Dspevx('V', 'A', Upper, 2, d, 0.0, 0.0, 0, 0, 0.0, x, z.Off(0, 0).UpdateRows(1), w, &iw, &i3)
		chkxer2("Dspevx", err)
		nt = nt + 10

		//     Test error exits for the sb path.
	} else if c2 == "sb" {
		//        Dsbtrd
		*srnamt = "Dsbtrd"
		*errt = fmt.Errorf("!wantq && vect != 'N': vect='/'")
		err = golapack.Dsbtrd('/', Upper, 0, 0, a.Off(0, 0).UpdateRows(1), d, e, z.Off(0, 0).UpdateRows(1), w)
		chkxer2("Dsbtrd", err)
		*errt = fmt.Errorf("!upper && uplo != Lower: uplo=Unrecognized: /")
		err = golapack.Dsbtrd('N', '/', 0, 0, a.Off(0, 0).UpdateRows(1), d, e, z.Off(0, 0).UpdateRows(1), w)
		chkxer2("Dsbtrd", err)
		*errt = fmt.Errorf("n < 0: n=-1")
		err = golapack.Dsbtrd('N', Upper, -1, 0, a.Off(0, 0).UpdateRows(1), d, e, z.Off(0, 0).UpdateRows(1), w)
		chkxer2("Dsbtrd", err)
		*errt = fmt.Errorf("kd < 0: kd=-1")
		err = golapack.Dsbtrd('N', Upper, 0, -1, a.Off(0, 0).UpdateRows(1), d, e, z.Off(0, 0).UpdateRows(1), w)
		chkxer2("Dsbtrd", err)
		*errt = fmt.Errorf("ab.Rows < kd1: ab.Rows=1, kd1=2")
		err = golapack.Dsbtrd('N', Upper, 1, 1, a.Off(0, 0).UpdateRows(1), d, e, z.Off(0, 0).UpdateRows(1), w)
		chkxer2("Dsbtrd", err)
		*errt = fmt.Errorf("q.Rows < max(1, n) && wantq: vect='V', q.Rows=1, n=2")
		err = golapack.Dsbtrd('V', Upper, 2, 0, a.Off(0, 0).UpdateRows(1), d, e, z.Off(0, 0).UpdateRows(1), w)
		chkxer2("Dsbtrd", err)
		nt = nt + 6

		//        DsytrdSb2st
		*srnamt = "DsytrdSb2st"
		*errt = fmt.Errorf("!afters1 && stage1 != 'N': stage1='/'")
		err = golapack.DsytrdSb2st('/', 'N', Upper, 0, 0, a.Off(0, 0).UpdateRows(1), d, e, r, 1, w, 1)
		chkxer2("DsytrdSb2st", err)
		*errt = fmt.Errorf("vect != 'N': vect='/'")
		err = golapack.DsytrdSb2st('N', '/', Upper, 0, 0, a.Off(0, 0).UpdateRows(1), d, e, r, 1, w, 1)
		chkxer2("DsytrdSb2st", err)
		*errt = fmt.Errorf("vect != 'N': vect='H'")
		err = golapack.DsytrdSb2st('N', 'H', Upper, 0, 0, a.Off(0, 0).UpdateRows(1), d, e, r, 1, w, 1)
		chkxer2("DsytrdSb2st", err)
		*errt = fmt.Errorf("!upper && uplo != Lower: uplo=Unrecognized: /")
		err = golapack.DsytrdSb2st('N', 'N', '/', 0, 0, a.Off(0, 0).UpdateRows(1), d, e, r, 1, w, 1)
		chkxer2("DsytrdSb2st", err)
		*errt = fmt.Errorf("n < 0: n=-1")
		err = golapack.DsytrdSb2st('N', 'N', Upper, -1, 0, a.Off(0, 0).UpdateRows(1), d, e, r, 1, w, 1)
		chkxer2("DsytrdSb2st", err)
		*errt = fmt.Errorf("kd < 0: kd=-1")
		err = golapack.DsytrdSb2st('N', 'N', Upper, 0, -1, a.Off(0, 0).UpdateRows(1), d, e, r, 1, w, 1)
		chkxer2("DsytrdSb2st", err)
		*errt = fmt.Errorf("ab.Rows < (kd + 1): ab.Rows=1, kd=1")
		err = golapack.DsytrdSb2st('N', 'N', Upper, 0, 1, a.Off(0, 0).UpdateRows(1), d, e, r, 1, w, 1)
		chkxer2("DsytrdSb2st", err)
		*errt = fmt.Errorf("lhous < lhmin && !lquery: lhous=0, lhmin=1, lquery=false")
		err = golapack.DsytrdSb2st('N', 'N', Upper, 0, 0, a.Off(0, 0).UpdateRows(1), d, e, r, 0, w, 1)
		chkxer2("DsytrdSb2st", err)
		*errt = fmt.Errorf("lwork < lwmin && !lquery: lwork=0, lwmin=1, lquery=false")
		err = golapack.DsytrdSb2st('N', 'N', Upper, 0, 0, a.Off(0, 0).UpdateRows(1), d, e, r, 1, w, 0)
		chkxer2("DsytrdSb2st", err)
		nt = nt + 9

		//        Dsbevd
		*srnamt = "Dsbevd"
		*errt = fmt.Errorf("!(wantz || jobz == 'N'): jobz='/'")
		_, err = golapack.Dsbevd('/', Upper, 0, 0, a.Off(0, 0).UpdateRows(1), x, z.Off(0, 0).UpdateRows(1), w, 1, &iw, 1)
		chkxer2("Dsbevd", err)
		*errt = fmt.Errorf("!(lower || uplo == Upper): uplo=Unrecognized: /")
		_, err = golapack.Dsbevd('N', '/', 0, 0, a.Off(0, 0).UpdateRows(1), x, z.Off(0, 0).UpdateRows(1), w, 1, &iw, 1)
		chkxer2("Dsbevd", err)
		*errt = fmt.Errorf("n < 0: n=-1")
		_, err = golapack.Dsbevd('N', Upper, -1, 0, a.Off(0, 0).UpdateRows(1), x, z.Off(0, 0).UpdateRows(1), w, 1, &iw, 1)
		chkxer2("Dsbevd", err)
		*errt = fmt.Errorf("kd < 0: kd=-1")
		_, err = golapack.Dsbevd('N', Upper, 0, -1, a.Off(0, 0).UpdateRows(1), x, z.Off(0, 0).UpdateRows(1), w, 1, &iw, 1)
		chkxer2("Dsbevd", err)
		*errt = fmt.Errorf("ab.Rows < kd+1: ab.Rows=1, kd=1")
		_, err = golapack.Dsbevd('N', Upper, 2, 1, a.Off(0, 0).UpdateRows(1), x, z.Off(0, 0).UpdateRows(1), w, 4, &iw, 1)
		chkxer2("Dsbevd", err)
		*errt = fmt.Errorf("z.Rows < 1 || (wantz && z.Rows < n): jobz='V', z.Rows=1, n=2")
		_, err = golapack.Dsbevd('V', Upper, 2, 1, a.Off(0, 0).UpdateRows(2), x, z.Off(0, 0).UpdateRows(1), w, 25, &iw, 12)
		chkxer2("Dsbevd", err)
		*errt = fmt.Errorf("lwork < lwmin && !lquery: lwork=0, lwmin=1, lquery=false")
		_, err = golapack.Dsbevd('N', Upper, 1, 0, a.Off(0, 0).UpdateRows(1), x, z.Off(0, 0).UpdateRows(1), w, 0, &iw, 1)
		chkxer2("Dsbevd", err)
		*errt = fmt.Errorf("lwork < lwmin && !lquery: lwork=3, lwmin=4, lquery=false")
		_, err = golapack.Dsbevd('N', Upper, 2, 0, a.Off(0, 0).UpdateRows(1), x, z.Off(0, 0).UpdateRows(1), w, 3, &iw, 1)
		chkxer2("Dsbevd", err)
		*errt = fmt.Errorf("lwork < lwmin && !lquery: lwork=18, lwmin=19, lquery=false")
		_, err = golapack.Dsbevd('V', Upper, 2, 0, a.Off(0, 0).UpdateRows(1), x, z.Off(0, 0).UpdateRows(2), w, 18, &iw, 12)
		chkxer2("Dsbevd", err)
		*errt = fmt.Errorf("liwork < liwmin && !lquery: liwork=0, liwmin=1, lquery=false")
		_, err = golapack.Dsbevd('N', Upper, 1, 0, a.Off(0, 0).UpdateRows(1), x, z.Off(0, 0).UpdateRows(1), w, 1, &iw, 0)
		chkxer2("Dsbevd", err)
		*errt = fmt.Errorf("liwork < liwmin && !lquery: liwork=11, liwmin=13, lquery=false")
		_, err = golapack.Dsbevd('V', Upper, 2, 0, a.Off(0, 0).UpdateRows(1), x, z.Off(0, 0).UpdateRows(2), w, 25, &iw, 11)
		chkxer2("Dsbevd", err)
		nt = nt + 11

		//        Dsbevd2stage
		*srnamt = "Dsbevd2stage"
		*errt = fmt.Errorf("jobz != 'N': jobz='/'")
		_, err = golapack.Dsbevd2stage('/', Upper, 0, 0, a.Off(0, 0).UpdateRows(1), x, z.Off(0, 0).UpdateRows(1), w, 1, &iw, 1)
		chkxer2("Dsbevd2stage", err)
		*errt = fmt.Errorf("jobz != 'N': jobz='V'")
		_, err = golapack.Dsbevd2stage('V', Upper, 0, 0, a.Off(0, 0).UpdateRows(1), x, z.Off(0, 0).UpdateRows(1), w, 1, &iw, 1)
		chkxer2("Dsbevd2stage", err)
		*errt = fmt.Errorf("!(lower || uplo == Upper): uplo=Unrecognized: /")
		_, err = golapack.Dsbevd2stage('N', '/', 0, 0, a.Off(0, 0).UpdateRows(1), x, z.Off(0, 0).UpdateRows(1), w, 1, &iw, 1)
		chkxer2("Dsbevd2stage", err)
		*errt = fmt.Errorf("n < 0: n=-1")
		_, err = golapack.Dsbevd2stage('N', Upper, -1, 0, a.Off(0, 0).UpdateRows(1), x, z.Off(0, 0).UpdateRows(1), w, 1, &iw, 1)
		chkxer2("Dsbevd2stage", err)
		*errt = fmt.Errorf("kd < 0: kd=-1")
		_, err = golapack.Dsbevd2stage('N', Upper, 0, -1, a.Off(0, 0).UpdateRows(1), x, z.Off(0, 0).UpdateRows(1), w, 1, &iw, 1)
		chkxer2("Dsbevd2stage", err)
		*errt = fmt.Errorf("ab.Rows < kd+1: ab.Rows=1, kd=1")
		_, err = golapack.Dsbevd2stage('N', Upper, 2, 1, a.Off(0, 0).UpdateRows(1), x, z.Off(0, 0).UpdateRows(1), w, 4, &iw, 1)
		chkxer2("Dsbevd2stage", err)
		// *errt = fmt.Errorf("z.Rows < 1 || (wantz && z.Rows < n): jobz='N', z.Rows=1, n=1")
		*errt = fmt.Errorf("lwork < lwmin && !lquery: lwork=0, lwmin=1, lquery=false")
		_, err = golapack.Dsbevd2stage('N', Upper, 1, 0, a.Off(0, 0).UpdateRows(1), x, z.Off(0, 0).UpdateRows(1), w, 0, &iw, 1)
		chkxer2("Dsbevd2stage", err)
		*errt = fmt.Errorf("lwork < lwmin && !lquery: lwork=3, lwmin=12, lquery=false")
		_, err = golapack.Dsbevd2stage('N', Upper, 2, 0, a.Off(0, 0).UpdateRows(1), x, z.Off(0, 0).UpdateRows(1), w, 3, &iw, 1)
		chkxer2("Dsbevd2stage", err)
		*errt = fmt.Errorf("liwork < liwmin && !lquery: liwork=0, liwmin=1, lquery=false")
		_, err = golapack.Dsbevd2stage('N', Upper, 1, 0, a.Off(0, 0).UpdateRows(1), x, z.Off(0, 0).UpdateRows(1), w, 1, &iw, 0)
		chkxer2("Dsbevd2stage", err)
		nt = nt + 9

		//        Dsbev
		*srnamt = "Dsbev"
		*errt = fmt.Errorf("!(wantz || jobz == 'N'): jobz='/'")
		_, err = golapack.Dsbev('/', Upper, 0, 0, a.Off(0, 0).UpdateRows(1), x, z.Off(0, 0).UpdateRows(1), w)
		chkxer2("Dsbev", err)
		*errt = fmt.Errorf("!(lower || uplo == Upper): uplo=Unrecognized: /")
		_, err = golapack.Dsbev('N', '/', 0, 0, a.Off(0, 0).UpdateRows(1), x, z.Off(0, 0).UpdateRows(1), w)
		chkxer2("Dsbev", err)
		*errt = fmt.Errorf("n < 0: n=-1")
		_, err = golapack.Dsbev('N', Upper, -1, 0, a.Off(0, 0).UpdateRows(1), x, z.Off(0, 0).UpdateRows(1), w)
		chkxer2("Dsbev", err)
		*errt = fmt.Errorf("kd < 0: kd=-1")
		_, err = golapack.Dsbev('N', Upper, 0, -1, a.Off(0, 0).UpdateRows(1), x, z.Off(0, 0).UpdateRows(1), w)
		chkxer2("Dsbev", err)
		*errt = fmt.Errorf("ab.Rows < kd+1: ab.Rows=1, kd=1")
		_, err = golapack.Dsbev('N', Upper, 2, 1, a.Off(0, 0).UpdateRows(1), x, z.Off(0, 0).UpdateRows(1), w)
		chkxer2("Dsbev", err)
		*errt = fmt.Errorf("z.Rows < 1 || (wantz && z.Rows < n): jobz='V', z.Rows=1, n=2")
		_, err = golapack.Dsbev('V', Upper, 2, 0, a.Off(0, 0).UpdateRows(1), x, z.Off(0, 0).UpdateRows(1), w)
		chkxer2("Dsbev", err)
		nt = nt + 6

		//        Dsbev2stage
		*srnamt = "Dsbev2stage"
		*errt = fmt.Errorf("jobz != 'N': jobz='/'")
		_, err = golapack.Dsbev2stage('/', Upper, 0, 0, a.Off(0, 0).UpdateRows(1), x, z.Off(0, 0).UpdateRows(1), w, 0)
		chkxer2("Dsbev2stage", err)
		*errt = fmt.Errorf("jobz != 'N': jobz='V'")
		_, err = golapack.Dsbev2stage('V', Upper, 0, 0, a.Off(0, 0).UpdateRows(1), x, z.Off(0, 0).UpdateRows(1), w, 0)
		chkxer2("Dsbev2stage", err)
		*errt = fmt.Errorf("!(lower || uplo == Upper): uplo=Unrecognized: /")
		_, err = golapack.Dsbev2stage('N', '/', 0, 0, a.Off(0, 0).UpdateRows(1), x, z.Off(0, 0).UpdateRows(1), w, 0)
		chkxer2("Dsbev2stage", err)
		*errt = fmt.Errorf("n < 0: n=-1")
		_, err = golapack.Dsbev2stage('N', Upper, -1, 0, a.Off(0, 0).UpdateRows(1), x, z.Off(0, 0).UpdateRows(1), w, 0)
		chkxer2("Dsbev2stage", err)
		*errt = fmt.Errorf("kd < 0: kd=-1")
		_, err = golapack.Dsbev2stage('N', Upper, 0, -1, a.Off(0, 0).UpdateRows(1), x, z.Off(0, 0).UpdateRows(1), w, 0)
		chkxer2("Dsbev2stage", err)
		*errt = fmt.Errorf("ab.Rows < kd+1: ab.Rows=1, kd=1")
		_, err = golapack.Dsbev2stage('N', Upper, 2, 1, a.Off(0, 0).UpdateRows(1), x, z.Off(0, 0).UpdateRows(1), w, 0)
		chkxer2("Dsbev2stage", err)
		// *errt = fmt.Errorf("z.Rows < 1 || (wantz && z.Rows < n): jobz='N', z.Rows=1, n=2")
		// _, err = golapack.Dsbev2stage('N', Upper, 3, 0, a.Off(0, 0).UpdateRows(3), x, z.Off(0, 0).UpdateRows(1), w, 0)
		// chkxer2("Dsbev2stage", err)
		*errt = fmt.Errorf("lwork < lwmin && !lquery: lwork=0, lwmin=1, lquery=false")
		_, err = golapack.Dsbev2stage('N', Upper, 0, 0, a.Off(0, 0).UpdateRows(1), x, z.Off(0, 0).UpdateRows(1), w, 0)
		chkxer2("Dsbev2stage", err)
		nt = nt + 8

		//        Dsbevx
		*srnamt = "Dsbevx"
		*errt = fmt.Errorf("!(wantz || jobz == 'N'): jobz='/'")
		_, _, err = golapack.Dsbevx('/', 'A', Upper, 0, 0, a.Off(0, 0).UpdateRows(1), q.Off(0, 0).UpdateRows(1), 0.0, 0.0, 0, 0, 0.0, x, z.Off(0, 0).UpdateRows(1), w, &iw, &i3)
		chkxer2("Dsbevx", err)
		*errt = fmt.Errorf("!(alleig || valeig || indeig): _range='/'")
		_, _, err = golapack.Dsbevx('N', '/', Upper, 0, 0, a.Off(0, 0).UpdateRows(1), q.Off(0, 0).UpdateRows(1), 0.0, 0.0, 0, 0, 0.0, x, z.Off(0, 0).UpdateRows(1), w, &iw, &i3)
		chkxer2("Dsbevx", err)
		*errt = fmt.Errorf("!(lower || uplo == Upper): uplo=Unrecognized: /")
		_, _, err = golapack.Dsbevx('N', 'A', '/', 0, 0, a.Off(0, 0).UpdateRows(1), q.Off(0, 0).UpdateRows(1), 0.0, 0.0, 0, 0, 0.0, x, z.Off(0, 0).UpdateRows(1), w, &iw, &i3)
		chkxer2("Dsbevx", err)
		*errt = fmt.Errorf("n < 0:n=-1")
		_, _, err = golapack.Dsbevx('N', 'A', Upper, -1, 0, a.Off(0, 0).UpdateRows(1), q.Off(0, 0).UpdateRows(1), 0.0, 0.0, 0, 0, 0.0, x, z.Off(0, 0).UpdateRows(1), w, &iw, &i3)
		chkxer2("Dsbevx", err)
		*errt = fmt.Errorf("kd < 0: kd=-1")
		_, _, err = golapack.Dsbevx('N', 'A', Upper, 0, -1, a.Off(0, 0).UpdateRows(1), q.Off(0, 0).UpdateRows(1), 0.0, 0.0, 0, 0, 0.0, x, z.Off(0, 0).UpdateRows(1), w, &iw, &i3)
		chkxer2("Dsbevx", err)
		*errt = fmt.Errorf("ab.Rows < kd+1: ab.Rows=1, kd=1")
		_, _, err = golapack.Dsbevx('N', 'A', Upper, 2, 1, a.Off(0, 0).UpdateRows(1), q.Off(0, 0).UpdateRows(1), 0.0, 0.0, 0, 0, 0.0, x, z.Off(0, 0).UpdateRows(1), w, &iw, &i3)
		chkxer2("Dsbevx", err)
		*errt = fmt.Errorf("wantz && q.Rows < max(1, n): jobz='V', q.Rows=1, n=2")
		_, _, err = golapack.Dsbevx('V', 'A', Upper, 2, 0, a.Off(0, 0).UpdateRows(1), q.Off(0, 0).UpdateRows(1), 0.0, 0.0, 0, 0, 0.0, x, z.Off(0, 0).UpdateRows(2), w, &iw, &i3)
		chkxer2("Dsbevx", err)
		*errt = fmt.Errorf("n > 0 && vu <= vl: n=1, vu=0, vl=0")
		_, _, err = golapack.Dsbevx('N', 'V', Upper, 1, 0, a.Off(0, 0).UpdateRows(1), q.Off(0, 0).UpdateRows(1), 0.0, 0.0, 0, 0, 0.0, x, z.Off(0, 0).UpdateRows(1), w, &iw, &i3)
		chkxer2("Dsbevx", err)
		*errt = fmt.Errorf("il < 1 || il > max(1, n): il=0, n=1")
		_, _, err = golapack.Dsbevx('N', 'I', Upper, 1, 0, a.Off(0, 0).UpdateRows(1), q.Off(0, 0).UpdateRows(1), 0.0, 0.0, 0, 0, 0.0, x, z.Off(0, 0).UpdateRows(1), w, &iw, &i3)
		chkxer2("Dsbevx", err)
		*errt = fmt.Errorf("il < 1 || il > max(1, n): il=2, n=1")
		_, _, err = golapack.Dsbevx('N', 'I', Upper, 1, 0, a.Off(0, 0).UpdateRows(1), q.Off(0, 0).UpdateRows(1), 0.0, 0.0, 2, 1, 0.0, x, z.Off(0, 0).UpdateRows(1), w, &iw, &i3)
		chkxer2("Dsbevx", err)
		*errt = fmt.Errorf("iu < min(*n, il) || iu > n: iu=1, il=2, n=2")
		_, _, err = golapack.Dsbevx('N', 'I', Upper, 2, 0, a.Off(0, 0).UpdateRows(1), q.Off(0, 0).UpdateRows(1), 0.0, 0.0, 2, 1, 0.0, x, z.Off(0, 0).UpdateRows(1), w, &iw, &i3)
		chkxer2("Dsbevx", err)
		*errt = fmt.Errorf("iu < min(*n, il) || iu > n: iu=2, il=1, n=1")
		_, _, err = golapack.Dsbevx('N', 'I', Upper, 1, 0, a.Off(0, 0).UpdateRows(1), q.Off(0, 0).UpdateRows(1), 0.0, 0.0, 1, 2, 0.0, x, z.Off(0, 0).UpdateRows(1), w, &iw, &i3)
		chkxer2("Dsbevx", err)
		*errt = fmt.Errorf("z.Rows < 1 || (wantz && z.Rows < n): jobz='V', z.Rows=1, n=2")
		_, _, err = golapack.Dsbevx('V', 'A', Upper, 2, 0, a.Off(0, 0).UpdateRows(1), q.Off(0, 0).UpdateRows(2), 0.0, 0.0, 0, 0, 0.0, x, z.Off(0, 0).UpdateRows(1), w, &iw, &i3)
		chkxer2("Dsbevx", err)
		nt = nt + 13

		//        Dsbevx2stage
		*srnamt = "Dsbevx2stage"
		// *errt = fmt.Errorf("z.Rows < 1 || (wantz && z.Rows < n): jobz='%c', z.Rows=%v, n=%v", jobz, z.Rows, n)
		*errt = fmt.Errorf("jobz != 'N': jobz='/'")
		_, _, err = golapack.Dsbevx2stage('/', 'A', Upper, 0, 0, a.Off(0, 0).UpdateRows(1), q.Off(0, 0).UpdateRows(1), 0.0, 0.0, 0, 0, 0.0, x, z.Off(0, 0).UpdateRows(1), w, 0, &iw, &i3)
		chkxer2("Dsbevx2stage", err)
		*errt = fmt.Errorf("jobz != 'N': jobz='V'")
		_, _, err = golapack.Dsbevx2stage('V', 'A', Upper, 0, 0, a.Off(0, 0).UpdateRows(1), q.Off(0, 0).UpdateRows(1), 0.0, 0.0, 0, 0, 0.0, x, z.Off(0, 0).UpdateRows(1), w, 0, &iw, &i3)
		chkxer2("Dsbevx2stage", err)
		*errt = fmt.Errorf("!(alleig || valeig || indeig): _range='/'")
		_, _, err = golapack.Dsbevx2stage('N', '/', Upper, 0, 0, a.Off(0, 0).UpdateRows(1), q.Off(0, 0).UpdateRows(1), 0.0, 0.0, 0, 0, 0.0, x, z.Off(0, 0).UpdateRows(1), w, 0, &iw, &i3)
		chkxer2("Dsbevx2stage", err)
		*errt = fmt.Errorf("!(lower || uplo == Upper): uplo=Unrecognized: /")
		_, _, err = golapack.Dsbevx2stage('N', 'A', '/', 0, 0, a.Off(0, 0).UpdateRows(1), q.Off(0, 0).UpdateRows(1), 0.0, 0.0, 0, 0, 0.0, x, z.Off(0, 0).UpdateRows(1), w, 0, &iw, &i3)
		chkxer2("Dsbevx2stage", err)
		*errt = fmt.Errorf("n < 0: n=-1")
		_, _, err = golapack.Dsbevx2stage('N', 'A', Upper, -1, 0, a.Off(0, 0).UpdateRows(1), q.Off(0, 0).UpdateRows(1), 0.0, 0.0, 0, 0, 0.0, x, z.Off(0, 0).UpdateRows(1), w, 0, &iw, &i3)
		chkxer2("Dsbevx2stage", err)
		*errt = fmt.Errorf("kd < 0: kd=-1")
		_, _, err = golapack.Dsbevx2stage('N', 'A', Upper, 0, -1, a.Off(0, 0).UpdateRows(1), q.Off(0, 0).UpdateRows(1), 0.0, 0.0, 0, 0, 0.0, x, z.Off(0, 0).UpdateRows(1), w, 0, &iw, &i3)
		chkxer2("Dsbevx2stage", err)
		*errt = fmt.Errorf("ab.Rows < kd+1: ab.Rows=1, kd=1")
		_, _, err = golapack.Dsbevx2stage('N', 'A', Upper, 2, 1, a.Off(0, 0).UpdateRows(1), q.Off(0, 0).UpdateRows(1), 0.0, 0.0, 0, 0, 0.0, x, z.Off(0, 0).UpdateRows(1), w, 0, &iw, &i3)
		chkxer2("Dsbevx2stage", err)
		// *errt = fmt.Errorf("wantz && q.Rows < max(1, n): jobz='N', q.Rows=1, n=1")
		*errt = fmt.Errorf("n > 0 && vu <= vl: n=1, vu=0, vl=0")
		_, _, err = golapack.Dsbevx2stage('N', 'V', Upper, 1, 0, a.Off(0, 0).UpdateRows(1), q.Off(0, 0).UpdateRows(1), 0.0, 0.0, 0, 0, 0.0, x, z.Off(0, 0).UpdateRows(1), w, 0, &iw, &i3)
		chkxer2("Dsbevx2stage", err)
		*errt = fmt.Errorf("il < 1 || il > max(1, n): il=0, n=1")
		_, _, err = golapack.Dsbevx2stage('N', 'I', Upper, 1, 0, a.Off(0, 0).UpdateRows(1), q.Off(0, 0).UpdateRows(1), 0.0, 0.0, 0, 0, 0.0, x, z.Off(0, 0).UpdateRows(1), w, 0, &iw, &i3)
		chkxer2("Dsbevx2stage", err)
		*errt = fmt.Errorf("il < 1 || il > max(1, n): il=2, n=1")
		_, _, err = golapack.Dsbevx2stage('N', 'I', Upper, 1, 0, a.Off(0, 0).UpdateRows(1), q.Off(0, 0).UpdateRows(1), 0.0, 0.0, 2, 1, 0.0, x, z.Off(0, 0).UpdateRows(1), w, 0, &iw, &i3)
		chkxer2("Dsbevx2stage", err)
		*errt = fmt.Errorf("iu < min(n, il) || iu > n: iu=1, il=2, n=2")
		_, _, err = golapack.Dsbevx2stage('N', 'I', Upper, 2, 0, a.Off(0, 0).UpdateRows(1), q.Off(0, 0).UpdateRows(1), 0.0, 0.0, 2, 1, 0.0, x, z.Off(0, 0).UpdateRows(1), w, 0, &iw, &i3)
		chkxer2("Dsbevx2stage", err)
		*errt = fmt.Errorf("iu < min(n, il) || iu > n: iu=2, il=1, n=1")
		_, _, err = golapack.Dsbevx2stage('N', 'I', Upper, 1, 0, a.Off(0, 0).UpdateRows(1), q.Off(0, 0).UpdateRows(1), 0.0, 0.0, 1, 2, 0.0, x, z.Off(0, 0).UpdateRows(1), w, 0, &iw, &i3)
		chkxer2("Dsbevx2stage", err)
		*errt = fmt.Errorf("lwork < lwmin && !lquery: lwork=0, lwmin=1, lquery=false")
		_, _, err = golapack.Dsbevx2stage('N', 'A', Upper, 0, 0, a.Off(0, 0).UpdateRows(1), q.Off(0, 0).UpdateRows(1), 0.0, 0.0, 0, 0, 0.0, x, z.Off(0, 0).UpdateRows(1), w, 0, &iw, &i3)
		chkxer2("Dsbevx2stage", err)
		nt = nt + 13
	}

	//     Print a summary line.
	if *ok {
		fmt.Printf(" %3s routines passed the tests of the error exits (%3d tests done)\n", path, nt)
	} else {
		fmt.Printf(" *** %3s routines failed the tests of the error exits ***\n", path)
	}

	if !(*ok) {
		t.Fail()
	}
}
