package eig

import (
	"fmt"
	"testing"

	"github.com/whipstein/golinalg/golapack"
	"github.com/whipstein/golinalg/golapack/gltest"
)

// zerrst tests the error exits for Zhetrd, Zungtr, CUNMTR, Zhptrd,
// Zungtr, Zupmtr, Zsteqr, CSTEIN, Zpteqr, Zhbtrd,
// ZHEEV, CHEEVX, CHEEVD, ZHBEV, CHBEVX, CHBEVD,
// ZHPEV, CHPEVX, CHPEVD, and Zstedc.
// Zheevd2stage, Zheevr2stage, Zheevx2stage,
// Zheev2stage, Zhbev2stage, Zhbevd2stage,
// Zhbevx2stage, Zhetrd2stage
func zerrst(path string, t *testing.T) (nt int) {
	var i, j, liw, lw, n, nmax int
	var err error

	nmax = 3
	liw = 12 * nmax
	lw = 20 * nmax
	tau := cvf(3)
	w := cvf(lw)
	d := vf(3)
	e := vf(3)
	r := vf(lw)
	rw := vf(lw)
	x := vf(3)
	i1 := make([]int, 3)
	i2 := make([]int, 3)
	i3 := make([]int, 3)
	iw := make([]int, liw)
	a := cmf(3, 3, opts)
	c := cmf(3, 3, opts)
	q := cmf(3, 3, opts)
	z := cmf(3, 3, opts)

	errt := &gltest.Common.Infoc.Errt
	infot := &gltest.Common.Infoc.Infot
	ok := &gltest.Common.Infoc.Ok
	srnamt := &gltest.Common.Srnamc.Srnamt

	c2 := path[1:3]

	//     Set the variables to innocuous values.
	for j = 1; j <= nmax; j++ {
		for i = 1; i <= nmax; i++ {
			a.SetRe(i-1, j-1, 1./float64(i+j))
		}
	}
	for j = 1; j <= nmax; j++ {
		d.Set(j-1, float64(j))
		e.Set(j-1, 0.0)
		i1[j-1] = j
		i2[j-1] = j
		tau.Set(j-1, 1.)
	}
	(*ok) = true
	nt = 0

	//     Test error exits for the st path.
	if c2 == "st" {
		//        Zhetrd
		*srnamt = "Zhetrd"
		*errt = fmt.Errorf("!upper && uplo != Lower: uplo=Unrecognized: /")
		err = golapack.Zhetrd('/', 0, a.Off(0, 0).UpdateRows(1), d, e, tau, w, 1)
		chkxer2("Zhetrd", err)
		*errt = fmt.Errorf("n < 0: n=-1")
		err = golapack.Zhetrd(Upper, -1, a.Off(0, 0).UpdateRows(1), d, e, tau, w, 1)
		chkxer2("Zhetrd", err)
		*errt = fmt.Errorf("a.Rows < max(1, n): a.Rows=1, n=2")
		err = golapack.Zhetrd(Upper, 2, a.Off(0, 0).UpdateRows(1), d, e, tau, w, 1)
		chkxer2("Zhetrd", err)
		*errt = fmt.Errorf("lwork < 1 && !lquery: lwork=0, lquery=false")
		err = golapack.Zhetrd(Upper, 0, a.Off(0, 0).UpdateRows(1), d, e, tau, w, 0)
		chkxer2("Zhetrd", err)
		nt = nt + 4

		//        Zhetrd2stage
		*srnamt = "Zhetrd2stage"
		*errt = fmt.Errorf("vect != 'N': vect='/'")
		err = golapack.Zhetrd2stage('/', Upper, 0, a.Off(0, 0).UpdateRows(1), d, e, tau, c.Off(0, 0).CVector(), 1, w, 1)
		chkxer2("Zhetrd2stage", err)
		*errt = fmt.Errorf("vect != 'N': vect='H'")
		err = golapack.Zhetrd2stage('H', Upper, 0, a.Off(0, 0).UpdateRows(1), d, e, tau, c.Off(0, 0).CVector(), 1, w, 1)
		chkxer2("Zhetrd2stage", err)
		*errt = fmt.Errorf("!upper && uplo != Lower: uplo=Unrecognized: /")
		err = golapack.Zhetrd2stage('N', '/', 0, a.Off(0, 0).UpdateRows(1), d, e, tau, c.Off(0, 0).CVector(), 1, w, 1)
		chkxer2("Zhetrd2stage", err)
		*errt = fmt.Errorf("n < 0: n=-1")
		err = golapack.Zhetrd2stage('N', Upper, -1, a.Off(0, 0).UpdateRows(1), d, e, tau, c.Off(0, 0).CVector(), 1, w, 1)
		chkxer2("Zhetrd2stage", err)
		*errt = fmt.Errorf("a.Rows < max(1, n): a.Rows=1, n=2")
		err = golapack.Zhetrd2stage('N', Upper, 2, a.Off(0, 0).UpdateRows(1), d, e, tau, c.Off(0, 0).CVector(), 1, w, 1)
		chkxer2("Zhetrd2stage", err)
		*errt = fmt.Errorf("lhous2 < lhmin && !lquery: lhous2=0, lhmin=1, lquery=false")
		err = golapack.Zhetrd2stage('N', Upper, 0, a.Off(0, 0).UpdateRows(1), d, e, tau, c.Off(0, 0).CVector(), 0, w, 1)
		chkxer2("Zhetrd2stage", err)
		*errt = fmt.Errorf("lwork < lwmin && !lquery: lwork=0, lwmin=1, lquery=false")
		err = golapack.Zhetrd2stage('N', Upper, 0, a.Off(0, 0).UpdateRows(1), d, e, tau, c.Off(0, 0).CVector(), 1, w, 0)
		chkxer2("Zhetrd2stage", err)
		nt = nt + 7

		//        ZhetrdHe2hb
		*srnamt = "ZhetrdHe2hb"
		*errt = fmt.Errorf("!upper && uplo != Lower: uplo=Unrecognized: /")
		err = golapack.ZhetrdHe2hb('/', 0, 0, a.Off(0, 0).UpdateRows(1), c.Off(0, 0).UpdateRows(1), tau, w, 1)
		chkxer2("ZhetrdHe2hb", err)
		*errt = fmt.Errorf("n < 0: n=-1")
		err = golapack.ZhetrdHe2hb(Upper, -1, 0, a.Off(0, 0).UpdateRows(1), c.Off(0, 0).UpdateRows(1), tau, w, 1)
		chkxer2("ZhetrdHe2hb", err)
		*errt = fmt.Errorf("kd < 0: kd=-1")
		err = golapack.ZhetrdHe2hb(Upper, 0, -1, a.Off(0, 0).UpdateRows(1), c.Off(0, 0).UpdateRows(1), tau, w, 1)
		chkxer2("ZhetrdHe2hb", err)
		*errt = fmt.Errorf("a.Rows < max(1, n): a.Rows=1, n=2")
		err = golapack.ZhetrdHe2hb(Upper, 2, 0, a.Off(0, 0).UpdateRows(1), c.Off(0, 0).UpdateRows(1), tau, w, 1)
		chkxer2("ZhetrdHe2hb", err)
		*errt = fmt.Errorf("ab.Rows < max(1, kd+1): ab.Rows=1, kd=2")
		err = golapack.ZhetrdHe2hb(Upper, 0, 2, a.Off(0, 0).UpdateRows(1), c.Off(0, 0).UpdateRows(1), tau, w, 1)
		chkxer2("ZhetrdHe2hb", err)
		*errt = fmt.Errorf("lwork < lwmin && !lquery: lwork=0, lwmin=1, lquery=false")
		err = golapack.ZhetrdHe2hb(Upper, 0, 0, a.Off(0, 0).UpdateRows(1), c.Off(0, 0).UpdateRows(1), tau, w, 0)
		chkxer2("ZhetrdHe2hb", err)
		nt = nt + 6

		//        ZhetrdHb2st
		*srnamt = "ZhetrdHb2st"
		*errt = fmt.Errorf("!afters1 && stage1 != 'N': stage1='/'")
		err = golapack.ZhetrdHb2st('/', 'N', Upper, 0, 0, a.Off(0, 0).UpdateRows(1), d, e, c.Off(0, 0).CVector(), 1, w, 1)
		chkxer2("ZhetrdHb2st", err)
		*errt = fmt.Errorf("vect != 'N': vect='/'")
		err = golapack.ZhetrdHb2st('Y', '/', Upper, 0, 0, a.Off(0, 0).UpdateRows(1), d, e, c.Off(0, 0).CVector(), 1, w, 1)
		chkxer2("ZhetrdHb2st", err)
		*errt = fmt.Errorf("vect != 'N': vect='H'")
		err = golapack.ZhetrdHb2st('Y', 'H', Upper, 0, 0, a.Off(0, 0).UpdateRows(1), d, e, c.Off(0, 0).CVector(), 1, w, 1)
		chkxer2("ZhetrdHb2st", err)
		*errt = fmt.Errorf("!upper && uplo != Lower: uplo=Unrecognized: /")
		err = golapack.ZhetrdHb2st('Y', 'N', '/', 0, 0, a.Off(0, 0).UpdateRows(1), d, e, c.Off(0, 0).CVector(), 1, w, 1)
		chkxer2("ZhetrdHb2st", err)
		*errt = fmt.Errorf("n < 0: n=-1")
		err = golapack.ZhetrdHb2st('Y', 'N', Upper, -1, 0, a.Off(0, 0).UpdateRows(1), d, e, c.Off(0, 0).CVector(), 1, w, 1)
		chkxer2("ZhetrdHb2st", err)
		*errt = fmt.Errorf("kd < 0: kd=-1")
		err = golapack.ZhetrdHb2st('Y', 'N', Upper, 0, -1, a.Off(0, 0).UpdateRows(1), d, e, c.Off(0, 0).CVector(), 1, w, 1)
		chkxer2("ZhetrdHb2st", err)
		*errt = fmt.Errorf("ab.Rows < (kd + 1): ab.Rows=1, kd=1")
		err = golapack.ZhetrdHb2st('Y', 'N', Upper, 0, 1, a.Off(0, 0).UpdateRows(1), d, e, c.Off(0, 0).CVector(), 1, w, 1)
		chkxer2("ZhetrdHb2st", err)
		*errt = fmt.Errorf("lhous < lhmin && !lquery: lhous=0, lhmin=1, lquery=false")
		err = golapack.ZhetrdHb2st('Y', 'N', Upper, 0, 0, a.Off(0, 0).UpdateRows(1), d, e, c.Off(0, 0).CVector(), 0, w, 1)
		chkxer2("ZhetrdHb2st", err)
		*errt = fmt.Errorf("lwork < lwmin && !lquery: lwork=0, lwmin=1, lquery=false")
		err = golapack.ZhetrdHb2st('Y', 'N', Upper, 0, 0, a.Off(0, 0).UpdateRows(1), d, e, c.Off(0, 0).CVector(), 1, w, 0)
		chkxer2("ZhetrdHb2st", err)
		nt = nt + 9

		//        Zungtr
		*srnamt = "Zungtr"
		*errt = fmt.Errorf("!upper && uplo != Lower: uplo=Unrecognized: /")
		err = golapack.Zungtr('/', 0, a.Off(0, 0).UpdateRows(1), tau, w, 1)
		chkxer2("Zungtr", err)
		*errt = fmt.Errorf("n < 0: n=-1")
		err = golapack.Zungtr(Upper, -1, a.Off(0, 0).UpdateRows(1), tau, w, 1)
		chkxer2("Zungtr", err)
		*errt = fmt.Errorf("a.Rows < max(1, n): a.Rows=1, n=2")
		err = golapack.Zungtr(Upper, 2, a.Off(0, 0).UpdateRows(1), tau, w, 1)
		chkxer2("Zungtr", err)
		*errt = fmt.Errorf("lwork < max(1, n-1) && !lquery: lwork=1, n=3, lquery=false")
		err = golapack.Zungtr(Upper, 3, a.Off(0, 0).UpdateRows(3), tau, w, 1)
		chkxer2("Zungtr", err)
		nt = nt + 4

		//        Zunmtr
		*srnamt = "Zunmtr"
		*errt = fmt.Errorf("!left && side != Right: side=Unrecognized: /")
		err = golapack.Zunmtr('/', Upper, NoTrans, 0, 0, a.Off(0, 0).UpdateRows(1), tau, c.Off(0, 0).UpdateRows(1), w, 1)
		chkxer2("Zunmtr", err)
		*errt = fmt.Errorf("!upper && uplo != Lower: uplo=Unrecognized: /")
		err = golapack.Zunmtr(Left, '/', NoTrans, 0, 0, a.Off(0, 0).UpdateRows(1), tau, c.Off(0, 0).UpdateRows(1), w, 1)
		chkxer2("Zunmtr", err)
		*errt = fmt.Errorf("trans != NoTrans && trans != ConjTrans: trans=Unrecognized: /")
		err = golapack.Zunmtr(Left, Upper, '/', 0, 0, a.Off(0, 0).UpdateRows(1), tau, c.Off(0, 0).UpdateRows(1), w, 1)
		chkxer2("Zunmtr", err)
		*errt = fmt.Errorf("m < 0: m=-1")
		err = golapack.Zunmtr(Left, Upper, NoTrans, -1, 0, a.Off(0, 0).UpdateRows(1), tau, c.Off(0, 0).UpdateRows(1), w, 1)
		chkxer2("Zunmtr", err)
		*errt = fmt.Errorf("n < 0: n=-1")
		err = golapack.Zunmtr(Left, Upper, NoTrans, 0, -1, a.Off(0, 0).UpdateRows(1), tau, c.Off(0, 0).UpdateRows(1), w, 1)
		chkxer2("Zunmtr", err)
		*errt = fmt.Errorf("a.Rows < max(1, nq): a.Rows=1, nq=2")
		err = golapack.Zunmtr(Left, Upper, NoTrans, 2, 0, a.Off(0, 0).UpdateRows(1), tau, c.Off(0, 0).UpdateRows(2), w, 1)
		chkxer2("Zunmtr", err)
		*errt = fmt.Errorf("a.Rows < max(1, nq): a.Rows=1, nq=2")
		err = golapack.Zunmtr(Right, Upper, NoTrans, 0, 2, a.Off(0, 0).UpdateRows(1), tau, c.Off(0, 0).UpdateRows(1), w, 1)
		chkxer2("Zunmtr", err)
		*errt = fmt.Errorf("c.Rows < max(1, m): c.Rows=1, m=2")
		err = golapack.Zunmtr(Left, Upper, NoTrans, 2, 0, a.Off(0, 0).UpdateRows(2), tau, c.Off(0, 0).UpdateRows(1), w, 1)
		chkxer2("Zunmtr", err)
		*errt = fmt.Errorf("lwork < max(1, nw) && !lquery: lwork=1, nw=2, lquery=false")
		err = golapack.Zunmtr(Left, Upper, NoTrans, 0, 2, a.Off(0, 0).UpdateRows(1), tau, c.Off(0, 0).UpdateRows(1), w, 1)
		chkxer2("Zunmtr", err)
		*errt = fmt.Errorf("lwork < max(1, nw) && !lquery: lwork=1, nw=2, lquery=false")
		err = golapack.Zunmtr(Right, Upper, NoTrans, 2, 0, a.Off(0, 0).UpdateRows(1), tau, c.Off(0, 0).UpdateRows(2), w, 1)
		chkxer2("Zunmtr", err)
		nt = nt + 10

		//        Zhptrd
		*srnamt = "Zhptrd"
		*errt = fmt.Errorf("!upper && uplo != Lower: uplo=Unrecognized: /")
		err = golapack.Zhptrd('/', 0, a.Off(0, 0).CVector(), d, e, tau)
		chkxer2("Zhptrd", err)
		*errt = fmt.Errorf("n < 0: n=-1")
		err = golapack.Zhptrd(Upper, -1, a.Off(0, 0).CVector(), d, e, tau)
		chkxer2("Zhptrd", err)
		nt = nt + 2

		//        Zupgtr
		*srnamt = "Zupgtr"
		*errt = fmt.Errorf("!upper && uplo != Lower: uplo=Unrecognized: /")
		err = golapack.Zupgtr('/', 0, a.Off(0, 0).CVector(), tau, z.Off(0, 0).UpdateRows(1), w)
		chkxer2("Zupgtr", err)
		*errt = fmt.Errorf("n < 0: n=-1")
		err = golapack.Zupgtr(Upper, -1, a.Off(0, 0).CVector(), tau, z.Off(0, 0).UpdateRows(1), w)
		chkxer2("Zupgtr", err)
		*errt = fmt.Errorf("q.Rows < max(1, n): q.Rows=1, n=2")
		err = golapack.Zupgtr(Upper, 2, a.Off(0, 0).CVector(), tau, z.Off(0, 0).UpdateRows(1), w)
		chkxer2("Zupgtr", err)
		nt = nt + 3

		//        Zupmtr
		*srnamt = "Zupmtr"
		*errt = fmt.Errorf("!left && side != Right: side=Unrecognized: /")
		err = golapack.Zupmtr('/', Upper, NoTrans, 0, 0, a.Off(0, 0).CVector(), tau, c.Off(0, 0).UpdateRows(1), w)
		chkxer2("Zupmtr", err)
		*errt = fmt.Errorf("!upper && uplo != Lower: uplo=Unrecognized: /")
		err = golapack.Zupmtr(Left, '/', NoTrans, 0, 0, a.Off(0, 0).CVector(), tau, c.Off(0, 0).UpdateRows(1), w)
		chkxer2("Zupmtr", err)
		*errt = fmt.Errorf("!notran && trans != ConjTrans: trans=Unrecognized: /")
		err = golapack.Zupmtr(Left, Upper, '/', 0, 0, a.Off(0, 0).CVector(), tau, c.Off(0, 0).UpdateRows(1), w)
		chkxer2("Zupmtr", err)
		*errt = fmt.Errorf("m < 0: m=-1")
		err = golapack.Zupmtr(Left, Upper, NoTrans, -1, 0, a.Off(0, 0).CVector(), tau, c.Off(0, 0).UpdateRows(1), w)
		chkxer2("Zupmtr", err)
		*errt = fmt.Errorf("n < 0: n=-1")
		err = golapack.Zupmtr(Left, Upper, NoTrans, 0, -1, a.Off(0, 0).CVector(), tau, c.Off(0, 0).UpdateRows(1), w)
		chkxer2("Zupmtr", err)
		*errt = fmt.Errorf("c.Rows < max(1, m): c.Rows=1, m=2")
		err = golapack.Zupmtr(Left, Upper, NoTrans, 2, 0, a.Off(0, 0).CVector(), tau, c.Off(0, 0).UpdateRows(1), w)
		chkxer2("Zupmtr", err)
		nt = nt + 6

		//        Zpteqr
		*srnamt = "Zpteqr"
		*errt = fmt.Errorf("icompz < 0: compz='/'")
		_, err = golapack.Zpteqr('/', 0, d, e, z.Off(0, 0).UpdateRows(1), rw)
		chkxer2("Zpteqr", err)
		*errt = fmt.Errorf("n < 0: n=-1")
		_, err = golapack.Zpteqr('N', -1, d, e, z.Off(0, 0).UpdateRows(1), rw)
		chkxer2("Zpteqr", err)
		*errt = fmt.Errorf("(z.Rows < 1) || (icompz > 0 && z.Rows < max(1, n)): compz='V', z.Rows=1, n=2")
		_, err = golapack.Zpteqr('V', 2, d, e, z.Off(0, 0).UpdateRows(1), rw)
		chkxer2("Zpteqr", err)
		nt = nt + 3

		//        Zstein
		*srnamt = "Zstein"
		// *errt = fmt.Errorf("(*iblock)[j-1] < (*iblock)[j]: iblock[j-1]=%v, iblock[j]=")
		// *errt = fmt.Errorf("(*iblock)[j-1] == (*iblock)[j] && w[j-1] < w[j]: iblock[j-1]=%v, iblock[j]=%v, w[j-1]=%v, w[j]=")
		*errt = fmt.Errorf("n < 0: n=-1")
		_, err = golapack.Zstein(-1, d, e, 0, x, &i1, &i2, z.Off(0, 0).UpdateRows(1), rw, &iw, &i3)
		chkxer2("Zstein", err)
		*errt = fmt.Errorf("m < 0 || m > n: m=-1, n=0")
		_, err = golapack.Zstein(0, d, e, -1, x, &i1, &i2, z.Off(0, 0).UpdateRows(1), rw, &iw, &i3)
		chkxer2("Zstein", err)
		*errt = fmt.Errorf("m < 0 || m > n: m=1, n=0")
		_, err = golapack.Zstein(0, d, e, 1, x, &i1, &i2, z.Off(0, 0).UpdateRows(1), rw, &iw, &i3)
		chkxer2("Zstein", err)
		*errt = fmt.Errorf("z.Rows < max(1, n): z.Rows=1, n=2")
		_, err = golapack.Zstein(2, d, e, 0, x, &i1, &i2, z.Off(0, 0).UpdateRows(1), rw, &iw, &i3)
		chkxer2("Zstein", err)
		nt = nt + 4

		//        Zsteqr
		*srnamt = "Zsteqr"
		*errt = fmt.Errorf("icompz < 0: compz='/'")
		_, err = golapack.Zsteqr('/', 0, d, e, z.Off(0, 0).UpdateRows(1), rw)
		chkxer2("Zsteqr", err)
		*errt = fmt.Errorf("n < 0: n=-1")
		_, err = golapack.Zsteqr('N', -1, d, e, z.Off(0, 0).UpdateRows(1), rw)
		chkxer2("Zsteqr", err)
		*errt = fmt.Errorf("(z.Rows < 1) || (icompz > 0 && z.Rows < max(1, n)): compz='V', z.Rows=1, n=2")
		_, err = golapack.Zsteqr('V', 2, d, e, z.Off(0, 0).UpdateRows(1), rw)
		chkxer2("Zsteqr", err)
		nt = nt + 3

		//        Zstedc
		*srnamt = "Zstedc"
		*errt = fmt.Errorf("icompz < 0: compz='/'")
		_, err = golapack.Zstedc('/', 0, d, e, z.Off(0, 0).UpdateRows(1), w, 1, rw, 1, &iw, 1)
		chkxer2("Zstedc", err)
		*errt = fmt.Errorf("n < 0: n=-1")
		_, err = golapack.Zstedc('N', -1, d, e, z.Off(0, 0).UpdateRows(1), w, 1, rw, 1, &iw, 1)
		chkxer2("Zstedc", err)
		*errt = fmt.Errorf("(z.Rows < 1) || (icompz > 0 && z.Rows < max(1, n)): compz='V', z.Rows=1, n=2")
		_, err = golapack.Zstedc('V', 2, d, e, z.Off(0, 0).UpdateRows(1), w, 4, rw, 23, &iw, 28)
		chkxer2("Zstedc", err)
		*errt = fmt.Errorf("lwork < lwmin && !lquery: lwork=0, lwmin=1, lquery=false")
		_, err = golapack.Zstedc('N', 2, d, e, z.Off(0, 0).UpdateRows(1), w, 0, rw, 1, &iw, 1)
		chkxer2("Zstedc", err)
		*errt = fmt.Errorf("lwork < lwmin && !lquery: lwork=0, lwmin=1, lquery=false")
		_, err = golapack.Zstedc('V', 2, d, e, z.Off(0, 0).UpdateRows(2), w, 0, rw, 23, &iw, 28)
		chkxer2("Zstedc", err)
		*errt = fmt.Errorf("lrwork < lrwmin && !lquery: lrwork=0, lrwmin=1, lquery=false")
		_, err = golapack.Zstedc('N', 2, d, e, z.Off(0, 0).UpdateRows(1), w, 1, rw, 0, &iw, 1)
		chkxer2("Zstedc", err)
		*errt = fmt.Errorf("lrwork < lrwmin && !lquery: lrwork=1, lrwmin=2, lquery=false")
		_, err = golapack.Zstedc('I', 2, d, e, z.Off(0, 0).UpdateRows(2), w, 1, rw, 1, &iw, 12)
		chkxer2("Zstedc", err)
		*errt = fmt.Errorf("lrwork < lrwmin && !lquery: lrwork=1, lrwmin=2, lquery=false")
		_, err = golapack.Zstedc('V', 2, d, e, z.Off(0, 0).UpdateRows(2), w, 4, rw, 1, &iw, 28)
		chkxer2("Zstedc", err)
		*errt = fmt.Errorf("liwork < liwmin && !lquery: liwork=0, liwmin=1, lquery=false")
		_, err = golapack.Zstedc('N', 2, d, e, z.Off(0, 0).UpdateRows(1), w, 1, rw, 1, &iw, 0)
		chkxer2("Zstedc", err)
		*errt = fmt.Errorf("liwork < liwmin && !lquery: liwork=0, liwmin=1, lquery=false")
		_, err = golapack.Zstedc('I', 2, d, e, z.Off(0, 0).UpdateRows(2), w, 1, rw, 23, &iw, 0)
		chkxer2("Zstedc", err)
		*errt = fmt.Errorf("liwork < liwmin && !lquery: liwork=0, liwmin=1, lquery=false")
		_, err = golapack.Zstedc('V', 2, d, e, z.Off(0, 0).UpdateRows(2), w, 4, rw, 23, &iw, 0)
		chkxer2("Zstedc", err)
		nt = nt + 11

		//        Zheevd
		*srnamt = "Zheevd"
		*errt = fmt.Errorf("!(wantz || jobz == 'N'): jobz='/'")
		_, err = golapack.Zheevd('/', Upper, 0, a.Off(0, 0).UpdateRows(1), x, w, 1, rw, 1, &iw, 1)
		chkxer2("Zheevd", err)
		*errt = fmt.Errorf("!(lower || uplo == Upper): uplo=Unrecognized: /")
		_, err = golapack.Zheevd('N', '/', 0, a.Off(0, 0).UpdateRows(1), x, w, 1, rw, 1, &iw, 1)
		chkxer2("Zheevd", err)
		*errt = fmt.Errorf("n < 0: n=-1")
		_, err = golapack.Zheevd('N', Upper, -1, a.Off(0, 0).UpdateRows(1), x, w, 1, rw, 1, &iw, 1)
		chkxer2("Zheevd", err)
		*errt = fmt.Errorf("a.Rows < max(1, n): a.Rows=1, n=2")
		_, err = golapack.Zheevd('N', Upper, 2, a.Off(0, 0).UpdateRows(1), x, w, 3, rw, 2, &iw, 1)
		chkxer2("Zheevd", err)
		*errt = fmt.Errorf("lwork < lwmin && !lquery: lwork=0, lwmin=1, lquery=false")
		_, err = golapack.Zheevd('N', Upper, 1, a.Off(0, 0).UpdateRows(1), x, w, 0, rw, 1, &iw, 1)
		chkxer2("Zheevd", err)
		*errt = fmt.Errorf("lwork < lwmin && !lquery: lwork=2, lwmin=3, lquery=false")
		_, err = golapack.Zheevd('N', Upper, 2, a.Off(0, 0).UpdateRows(2), x, w, 2, rw, 2, &iw, 1)
		chkxer2("Zheevd", err)
		*errt = fmt.Errorf("lwork < lwmin && !lquery: lwork=3, lwmin=8, lquery=false")
		_, err = golapack.Zheevd('V', Upper, 2, a.Off(0, 0).UpdateRows(2), x, w, 3, rw, 25, &iw, 12)
		chkxer2("Zheevd", err)
		*errt = fmt.Errorf("lrwork < lrwmin && !lquery: lrwork=0, lrwmin=1, lquery=false")
		_, err = golapack.Zheevd('N', Upper, 1, a.Off(0, 0).UpdateRows(1), x, w, 1, rw, 0, &iw, 1)
		chkxer2("Zheevd", err)
		*errt = fmt.Errorf("lrwork < lrwmin && !lquery: lrwork=1, lrwmin=2, lquery=false")
		_, err = golapack.Zheevd('N', Upper, 2, a.Off(0, 0).UpdateRows(2), x, w, 3, rw, 1, &iw, 1)
		chkxer2("Zheevd", err)
		*errt = fmt.Errorf("lrwork < lrwmin && !lquery: lrwork=18, lrwmin=19, lquery=false")
		_, err = golapack.Zheevd('V', Upper, 2, a.Off(0, 0).UpdateRows(2), x, w, 8, rw, 18, &iw, 12)
		chkxer2("Zheevd", err)
		*errt = fmt.Errorf("liwork < liwmin && !lquery: liwork=0, liwmin=1, lquery=false")
		_, err = golapack.Zheevd('N', Upper, 1, a.Off(0, 0).UpdateRows(1), x, w, 1, rw, 1, &iw, 0)
		chkxer2("Zheevd", err)
		*errt = fmt.Errorf("liwork < liwmin && !lquery: liwork=11, liwmin=13, lquery=false")
		_, err = golapack.Zheevd('V', Upper, 2, a.Off(0, 0).UpdateRows(2), x, w, 8, rw, 25, &iw, 11)
		chkxer2("Zheevd", err)
		nt = nt + 12

		//        Zheevd2stage
		*srnamt = "Zheevd2stage"
		*errt = fmt.Errorf("jobz != 'N': jobz='/'")
		_, err = golapack.Zheevd2stage('/', Upper, 0, a.Off(0, 0).UpdateRows(1), x, w, 1, rw, 1, &iw, 1)
		chkxer2("Zheevd2stage", err)
		*errt = fmt.Errorf("jobz != 'N': jobz='V'")
		_, err = golapack.Zheevd2stage('V', Upper, 0, a.Off(0, 0).UpdateRows(1), x, w, 1, rw, 1, &iw, 1)
		chkxer2("Zheevd2stage", err)
		*errt = fmt.Errorf("!(lower || uplo == Upper): uplo=Unrecognized: /")
		_, err = golapack.Zheevd2stage('N', '/', 0, a.Off(0, 0).UpdateRows(1), x, w, 1, rw, 1, &iw, 1)
		chkxer2("Zheevd2stage", err)
		*errt = fmt.Errorf("n < 0: n=-1")
		_, err = golapack.Zheevd2stage('N', Upper, -1, a.Off(0, 0).UpdateRows(1), x, w, 1, rw, 1, &iw, 1)
		chkxer2("Zheevd2stage", err)
		*errt = fmt.Errorf("a.Rows < max(1, n): a.Rows=1, n=2")
		_, err = golapack.Zheevd2stage('N', Upper, 2, a.Off(0, 0).UpdateRows(1), x, w, 3, rw, 2, &iw, 1)
		chkxer2("Zheevd2stage", err)
		*errt = fmt.Errorf("lwork < lwmin && !lquery: lwork=0, lwmin=1, lquery=false")
		_, err = golapack.Zheevd2stage('N', Upper, 1, a.Off(0, 0).UpdateRows(1), x, w, 0, rw, 1, &iw, 1)
		chkxer2("Zheevd2stage", err)
		*errt = fmt.Errorf("lwork < lwmin && !lquery: lwork=2, lwmin=12, lquery=false")
		_, err = golapack.Zheevd2stage('N', Upper, 2, a.Off(0, 0).UpdateRows(2), x, w, 2, rw, 2, &iw, 1)
		chkxer2("Zheevd2stage", err)
		*errt = fmt.Errorf("lrwork < lrwmin && !lquery: lrwork=0, lrwmin=1, lquery=false")
		_, err = golapack.Zheevd2stage('N', Upper, 1, a.Off(0, 0).UpdateRows(1), x, w, 1, rw, 0, &iw, 1)
		chkxer2("Zheevd2stage", err)
		// *errt = fmt.Errorf("lrwork < lrwmin && !lquery: lrwork=1, lrwmin=2, lquery=false")
		// _, err = golapack.Zheevd2stage('N', Upper, 2, a.Off(0, 0).UpdateRows(2), x, w, 700, rw, 1, &iw, 1)
		// chkxer2("Zheevd2stage", err)
		*errt = fmt.Errorf("liwork < liwmin && !lquery: liwork=0, liwmin=1, lquery=false")
		_, err = golapack.Zheevd2stage('N', Upper, 1, a.Off(0, 0).UpdateRows(1), x, w, 1, rw, 1, &iw, 0)
		chkxer2("Zheevd2stage", err)
		// *errt = fmt.Errorf("liwork < liwmin && !lquery: liwork=1, liwmin=2, lquery=false")
		// _, err = golapack.Zheevd2stage('N', Upper, 1, a.Off(0, 0).UpdateRows(1), x, w, 1, rw, 1, &iw, 1)
		// chkxer2("Zheevd2stage", err)
		nt = nt + 10

		//        ZHEEV
		*srnamt = "Zheev"
		*errt = fmt.Errorf("!(wantz || jobz == 'N'): jobz='/'")
		_, err = golapack.Zheev('/', Upper, 0, a.Off(0, 0).UpdateRows(1), x, w, 1, rw)
		chkxer2("Zheev", err)
		*errt = fmt.Errorf("!(lower || uplo == Upper): uplo=Unrecognized: /")
		_, err = golapack.Zheev('N', '/', 0, a.Off(0, 0).UpdateRows(1), x, w, 1, rw)
		chkxer2("Zheev", err)
		*errt = fmt.Errorf("n < 0: n=-1")
		_, err = golapack.Zheev('N', Upper, -1, a.Off(0, 0).UpdateRows(1), x, w, 1, rw)
		chkxer2("Zheev", err)
		*errt = fmt.Errorf("a.Rows < max(1, n): a.Rows=1, n=2")
		_, err = golapack.Zheev('N', Upper, 2, a.Off(0, 0).UpdateRows(1), x, w, 3, rw)
		chkxer2("Zheev", err)
		*errt = fmt.Errorf("lwork < max(1, 2*n-1) && !lquery: lwork=2, n=2, lquery=false")
		_, err = golapack.Zheev('N', Upper, 2, a.Off(0, 0).UpdateRows(2), x, w, 2, rw)
		chkxer2("Zheev", err)
		nt = nt + 5

		//        Zheev2stage
		*srnamt = "Zheev2stage"
		*errt = fmt.Errorf("jobz != 'N': jobz='/'")
		_, err = golapack.Zheev2stage('/', Upper, 0, a.Off(0, 0).UpdateRows(1), x, w, 1, rw)
		chkxer2("Zheev2stage", err)
		*errt = fmt.Errorf("jobz != 'N': jobz='V'")
		_, err = golapack.Zheev2stage('V', Upper, 0, a.Off(0, 0).UpdateRows(1), x, w, 1, rw)
		chkxer2("Zheev2stage", err)
		*errt = fmt.Errorf("!(lower || uplo == Upper): uplo=Unrecognized: /")
		_, err = golapack.Zheev2stage('N', '/', 0, a.Off(0, 0).UpdateRows(1), x, w, 1, rw)
		chkxer2("Zheev2stage", err)
		*errt = fmt.Errorf("n < 0: n=-1")
		_, err = golapack.Zheev2stage('N', Upper, -1, a.Off(0, 0).UpdateRows(1), x, w, 1, rw)
		chkxer2("Zheev2stage", err)
		*errt = fmt.Errorf("a.Rows < max(1, n): a.Rows=1, n=2")
		_, err = golapack.Zheev2stage('N', Upper, 2, a.Off(0, 0).UpdateRows(1), x, w, 3, rw)
		chkxer2("Zheev2stage", err)
		*errt = fmt.Errorf("lwork < lwmin && !lquery: lwork=2, lwmin=11, lquery=false")
		_, err = golapack.Zheev2stage('N', Upper, 2, a.Off(0, 0).UpdateRows(2), x, w, 2, rw)
		chkxer2("Zheev2stage", err)
		nt = nt + 6

		//        Zheevx
		*srnamt = "Zheevx"
		*errt = fmt.Errorf("!(wantz || jobz == 'N'): jobz='/'")
		_, _, err = golapack.Zheevx('/', 'A', Upper, 0, a.Off(0, 0).UpdateRows(1), 0.0, 0.0, 0, 0, 0.0, x, z.Off(0, 0).UpdateRows(1), w, 1, rw, &iw, &i3)
		chkxer2("Zheevx", err)
		*errt = fmt.Errorf("!(alleig || valeig || indeig): _range='/'")
		_, _, err = golapack.Zheevx('V', '/', Upper, 0, a.Off(0, 0).UpdateRows(1), 0.0, 1.0, 1, 0, 0.0, x, z.Off(0, 0).UpdateRows(1), w, 1, rw, &iw, &i3)
		chkxer2("Zheevx", err)
		*errt = fmt.Errorf("!(lower || uplo == Upper): uplo=Unrecognized: /")
		_, _, err = golapack.Zheevx('V', 'A', '/', 0, a.Off(0, 0).UpdateRows(1), 0.0, 0.0, 0, 0, 0.0, x, z.Off(0, 0).UpdateRows(1), w, 1, rw, &iw, &i3)
		chkxer2("Zheevx", err)
		*errt = fmt.Errorf("n < 0: n=-1")
		_, _, err = golapack.Zheevx('V', 'A', Upper, -1, a.Off(0, 0).UpdateRows(1), 0.0, 0.0, 0, 0, 0.0, x, z.Off(0, 0).UpdateRows(1), w, 1, rw, &iw, &i3)
		chkxer2("Zheevx", err)
		*errt = fmt.Errorf("a.Rows < max(1, n): a.Rows=1, n=2")
		_, _, err = golapack.Zheevx('V', 'A', Upper, 2, a.Off(0, 0).UpdateRows(1), 0.0, 0.0, 0, 0, 0.0, x, z.Off(0, 0).UpdateRows(2), w, 3, rw, &iw, &i3)
		chkxer2("Zheevx", err)
		*errt = fmt.Errorf("n > 0 && vu <= vl: n=1, vl=0, vu=0")
		_, _, err = golapack.Zheevx('V', 'V', Upper, 1, a.Off(0, 0).UpdateRows(1), 0.0, 0.0, 0, 0, 0.0, x, z.Off(0, 0).UpdateRows(1), w, 1, rw, &iw, &i3)
		chkxer2("Zheevx", err)
		*errt = fmt.Errorf("il < 1 || il > max(1, n): n=1, il=0")
		_, _, err = golapack.Zheevx('V', 'I', Upper, 1, a.Off(0, 0).UpdateRows(1), 0.0, 0.0, 0, 0, 0.0, x, z.Off(0, 0).UpdateRows(1), w, 1, rw, &iw, &i3)
		chkxer2("Zheevx", err)
		*errt = fmt.Errorf("iu < min(n, il) || iu > n: n=2, il=2, iu=1")
		_, _, err = golapack.Zheevx('V', 'I', Upper, 2, a.Off(0, 0).UpdateRows(2), 0.0, 0.0, 2, 1, 0.0, x, z.Off(0, 0).UpdateRows(2), w, 3, rw, &iw, &i3)
		chkxer2("Zheevx", err)
		*errt = fmt.Errorf("z.Rows < 1 || (wantz && z.Rows < n): jobz='V', z.Rows=1, n=2")
		_, _, err = golapack.Zheevx('V', 'A', Upper, 2, a.Off(0, 0).UpdateRows(2), 0.0, 0.0, 0, 0, 0.0, x, z.Off(0, 0).UpdateRows(1), w, 3, rw, &iw, &i3)
		chkxer2("Zheevx", err)
		*errt = fmt.Errorf("lwork < lwkmin && !lquery: lwork=2, lwkmin=4, lquery=false")
		_, _, err = golapack.Zheevx('V', 'A', Upper, 2, a.Off(0, 0).UpdateRows(2), 0.0, 0.0, 0, 0, 0.0, x, z.Off(0, 0).UpdateRows(2), w, 2, rw, &iw, &i1)
		chkxer2("Zheevx", err)
		nt = nt + 10

		//        Zheevx2stage
		*srnamt = "Zheevx2stage"
		*errt = fmt.Errorf("jobz != 'N': jobz='/'")
		_, _, err = golapack.Zheevx2stage('/', 'A', Upper, 0, a.Off(0, 0).UpdateRows(1), 0.0, 0.0, 0, 0, 0.0, x, z.Off(0, 0).UpdateRows(1), w, 1, rw, &iw, &i3)
		chkxer2("Zheevx2stage", err)
		*errt = fmt.Errorf("jobz != 'N': jobz='V'")
		_, _, err = golapack.Zheevx2stage('V', 'A', Upper, 0, a.Off(0, 0).UpdateRows(1), 0.0, 0.0, 0, 0, 0.0, x, z.Off(0, 0).UpdateRows(1), w, 1, rw, &iw, &i3)
		chkxer2("Zheevx2stage", err)
		*errt = fmt.Errorf("!(alleig || valeig || indeig): _range='/'")
		_, _, err = golapack.Zheevx2stage('N', '/', Upper, 0, a.Off(0, 0).UpdateRows(1), 0.0, 1.0, 1, 0, 0.0, x, z.Off(0, 0).UpdateRows(1), w, 1, rw, &iw, &i3)
		chkxer2("Zheevx2stage", err)
		*errt = fmt.Errorf("!(lower || uplo == Upper): uplo=Unrecognized: /")
		_, _, err = golapack.Zheevx2stage('N', 'A', '/', 0, a.Off(0, 0).UpdateRows(1), 0.0, 0.0, 0, 0, 0.0, x, z.Off(0, 0).UpdateRows(1), w, 1, rw, &iw, &i3)
		chkxer2("Zheevx2stage", err)
		*errt = fmt.Errorf("n < 0: n=-1")
		_, _, err = golapack.Zheevx2stage('N', 'A', Upper, -1, a.Off(0, 0).UpdateRows(1), 0.0, 0.0, 0, 0, 0.0, x, z.Off(0, 0).UpdateRows(1), w, 1, rw, &iw, &i3)
		chkxer2("Zheevx2stage", err)
		*errt = fmt.Errorf("a.Rows < max(1, n): a.Rows=1, n=2")
		_, _, err = golapack.Zheevx2stage('N', 'A', Upper, 2, a.Off(0, 0).UpdateRows(1), 0.0, 0.0, 0, 0, 0.0, x, z.Off(0, 0).UpdateRows(2), w, 3, rw, &iw, &i3)
		chkxer2("Zheevx2stage", err)
		*errt = fmt.Errorf("n > 0 && vu <= vl: n=1, vl=0, vu=0")
		_, _, err = golapack.Zheevx2stage('N', 'V', Upper, 1, a.Off(0, 0).UpdateRows(1), 0.0, 0.0, 0, 0, 0.0, x, z.Off(0, 0).UpdateRows(1), w, 1, rw, &iw, &i3)
		chkxer2("Zheevx2stage", err)
		*errt = fmt.Errorf("il < 1 || il > max(1, n): n=1, il=0")
		_, _, err = golapack.Zheevx2stage('N', 'I', Upper, 1, a.Off(0, 0).UpdateRows(1), 0.0, 0.0, 0, 0, 0.0, x, z.Off(0, 0).UpdateRows(1), w, 1, rw, &iw, &i3)
		chkxer2("Zheevx2stage", err)
		*errt = fmt.Errorf("iu < min(n, il) || iu > n: n=2, il=2, iu=1")
		_, _, err = golapack.Zheevx2stage('N', 'I', Upper, 2, a.Off(0, 0).UpdateRows(2), 0.0, 0.0, 2, 1, 0.0, x, z.Off(0, 0).UpdateRows(2), w, 3, rw, &iw, &i3)
		chkxer2("Zheevx2stage", err)
		*errt = fmt.Errorf("z.Rows < 1 || (wantz && z.Rows < n): jobz='N', z.Rows=-1, n=2")
		_, _, err = golapack.Zheevx2stage('N', 'A', Upper, 2, a.Off(0, 0).UpdateRows(2), 0.0, 0.0, 0, 0, 0.0, x, z.Off(0, 0).UpdateRows(-1), w, 3, rw, &iw, &i3)
		chkxer2("Zheevx2stage", err)
		*errt = fmt.Errorf("lwork < lwmin && !lquery: lwork=0, lwmin=11, lquery=false")
		_, _, err = golapack.Zheevx2stage('N', 'A', Upper, 2, a.Off(0, 0).UpdateRows(2), 0.0, 0.0, 0, 0, 0.0, x, z.Off(0, 0).UpdateRows(2), w, 0, rw, &iw, &i1)
		chkxer2("Zheevx2stage", err)
		nt = nt + 11

		//        Zheevr
		*srnamt = "Zheevr"
		n = 1
		*errt = fmt.Errorf("!(wantz || jobz == 'N'): jobz='/'")
		_, _, err = golapack.Zheevr('/', 'A', Upper, 0, a.Off(0, 0).UpdateRows(1), 0.0, 0.0, 1, 1, 0.0, r, z.Off(0, 0).UpdateRows(1), &iw, q.Off(0, 0).CVector(), 2*n, rw, 24*n, toSlice(&iw, 2*n), 10*n)
		chkxer2("Zheevr", err)
		*errt = fmt.Errorf("!(alleig || valeig || indeig): _range='/'")
		_, _, err = golapack.Zheevr('V', '/', Upper, 0, a.Off(0, 0).UpdateRows(1), 0.0, 0.0, 1, 1, 0.0, r, z.Off(0, 0).UpdateRows(1), &iw, q.Off(0, 0).CVector(), 2*n, rw, 24*n, toSlice(&iw, 2*n), 10*n)
		chkxer2("Zheevr", err)
		*errt = fmt.Errorf("!(lower || uplo == Upper): uplo=Unrecognized: /")
		_, _, err = golapack.Zheevr('V', 'A', '/', -1, a.Off(0, 0).UpdateRows(1), 0.0, 0.0, 1, 1, 0.0, r, z.Off(0, 0).UpdateRows(1), &iw, q.Off(0, 0).CVector(), 2*n, rw, 24*n, toSlice(&iw, 2*n), 10*n)
		chkxer2("Zheevr", err)
		*errt = fmt.Errorf("n < 0: n=-1")
		_, _, err = golapack.Zheevr('V', 'A', Upper, -1, a.Off(0, 0).UpdateRows(1), 0.0, 0.0, 1, 1, 0.0, r, z.Off(0, 0).UpdateRows(1), &iw, q.Off(0, 0).CVector(), 2*n, rw, 24*n, toSlice(&iw, 2*n), 10*n)
		chkxer2("Zheevr", err)
		*errt = fmt.Errorf("a.Rows < max(1, n): a.Rows=1, n=2")
		_, _, err = golapack.Zheevr('V', 'A', Upper, 2, a.Off(0, 0).UpdateRows(1), 0.0, 0.0, 1, 1, 0.0, r, z.Off(0, 0).UpdateRows(1), &iw, q.Off(0, 0).CVector(), 2*n, rw, 24*n, toSlice(&iw, 2*n), 10*n)
		chkxer2("Zheevr", err)
		*errt = fmt.Errorf("n > 0 && vu <= vl: n=1, vl=0, vu=0")
		_, _, err = golapack.Zheevr('V', 'V', Upper, 1, a.Off(0, 0).UpdateRows(1), 0.0, 0.0, 1, 1, 0.0, r, z.Off(0, 0).UpdateRows(1), &iw, q.Off(0, 0).CVector(), 2*n, rw, 24*n, toSlice(&iw, 2*n), 10*n)
		chkxer2("Zheevr", err)
		*errt = fmt.Errorf("il < 1 || il > max(1, n): n=1, il=0")
		_, _, err = golapack.Zheevr('V', 'I', Upper, 1, a.Off(0, 0).UpdateRows(1), 0.0, 0.0, 0, 1, 0.0, r, z.Off(0, 0).UpdateRows(1), &iw, q.Off(0, 0).CVector(), 2*n, rw, 24*n, toSlice(&iw, 2*n), 10*n)
		chkxer2("Zheevr", err)
		*errt = fmt.Errorf("iu < min(n, il) || iu > n: n=2, il=2, iu=1")
		_, _, err = golapack.Zheevr('V', 'I', Upper, 2, a.Off(0, 0).UpdateRows(2), 0.0, 0.0, 2, 1, 0.0, r, z.Off(0, 0).UpdateRows(1), &iw, q.Off(0, 0).CVector(), 2*n, rw, 24*n, toSlice(&iw, 2*n), 10*n)
		chkxer2("Zheevr", err)
		*errt = fmt.Errorf("z.Rows < 1 || (wantz && z.Rows < n): jobz='V', z.Rows=-1, n=1")
		_, _, err = golapack.Zheevr('V', 'I', Upper, 1, a.Off(0, 0).UpdateRows(1), 0.0, 0.0, 1, 1, 0.0, r, z.Off(0, 0).UpdateRows(-1), &iw, q.Off(0, 0).CVector(), 2*n, rw, 24*n, toSlice(&iw, 2*n), 10*n)
		chkxer2("Zheevr", err)
		*errt = fmt.Errorf("lwork < lwmin && !lquery: lwork=1, lwmin=2, lquery=false")
		_, _, err = golapack.Zheevr('V', 'I', Upper, 1, a.Off(0, 0).UpdateRows(1), 0.0, 0.0, 1, 1, 0.0, r, z.Off(0, 0).UpdateRows(1), &iw, q.Off(0, 0).CVector(), 2*n-1, rw, 24*n, toSlice(&iw, 2*n), 10*n)
		chkxer2("Zheevr", err)
		*errt = fmt.Errorf("lrwork < lrwmin && !lquery: lrwork=23, lrwmin=24, lquery=false")
		_, _, err = golapack.Zheevr('V', 'I', Upper, 1, a.Off(0, 0).UpdateRows(1), 0.0, 0.0, 1, 1, 0.0, r, z.Off(0, 0).UpdateRows(1), &iw, q.Off(0, 0).CVector(), 2*n, rw, 24*n-1, toSlice(&iw, 2*n-1-1), 10*n)
		chkxer2("Zheevr", err)
		*errt = fmt.Errorf("liwork < liwmin && !lquery: liwork=9, liwmin=10, lquery=false")
		_, _, err = golapack.Zheevr('V', 'I', Upper, 1, a.Off(0, 0).UpdateRows(1), 0.0, 0.0, 1, 1, 0.0, r, z.Off(0, 0).UpdateRows(1), &iw, q.Off(0, 0).CVector(), 2*n, rw, 24*n, &iw, 10*n-1)
		chkxer2("Zheevr", err)
		nt = nt + 12

		//        Zheevr2stage
		*srnamt = "Zheevr2stage"
		n = 1
		*errt = fmt.Errorf("jobz != 'N': jobz='/'")
		_, _, err = golapack.Zheevr2stage('/', 'A', Upper, 0, a.Off(0, 0).UpdateRows(1), 0.0, 0.0, 1, 1, 0.0, r, z.Off(0, 0).UpdateRows(1), &iw, q.Off(0, 0).CVector(), 2*n, rw, 24*n, toSlice(&iw, 2*n), 10*n)
		chkxer2("Zheevr2stage", err)
		*errt = fmt.Errorf("jobz != 'N': jobz='V'")
		_, _, err = golapack.Zheevr2stage('V', 'A', Upper, 0, a.Off(0, 0).UpdateRows(1), 0.0, 0.0, 1, 1, 0.0, r, z.Off(0, 0).UpdateRows(1), &iw, q.Off(0, 0).CVector(), 2*n, rw, 24*n, toSlice(&iw, 2*n), 10*n)
		chkxer2("Zheevr2stage", err)
		*errt = fmt.Errorf("!(alleig || valeig || indeig): _range='/'")
		_, _, err = golapack.Zheevr2stage('N', '/', Upper, 0, a.Off(0, 0).UpdateRows(1), 0.0, 0.0, 1, 1, 0.0, r, z.Off(0, 0).UpdateRows(1), &iw, q.Off(0, 0).CVector(), 2*n, rw, 24*n, toSlice(&iw, 2*n), 10*n)
		chkxer2("Zheevr2stage", err)
		*errt = fmt.Errorf("!(lower || uplo == Upper): uplo=Unrecognized: /")
		_, _, err = golapack.Zheevr2stage('N', 'A', '/', -1, a.Off(0, 0).UpdateRows(1), 0.0, 0.0, 1, 1, 0.0, r, z.Off(0, 0).UpdateRows(1), &iw, q.Off(0, 0).CVector(), 2*n, rw, 24*n, toSlice(&iw, 2*n), 10*n)
		chkxer2("Zheevr2stage", err)
		*errt = fmt.Errorf("n < 0: n=-1")
		_, _, err = golapack.Zheevr2stage('N', 'A', Upper, -1, a.Off(0, 0).UpdateRows(1), 0.0, 0.0, 1, 1, 0.0, r, z.Off(0, 0).UpdateRows(1), &iw, q.Off(0, 0).CVector(), 2*n, rw, 24*n, toSlice(&iw, 2*n), 10*n)
		chkxer2("Zheevr2stage", err)
		*errt = fmt.Errorf("a.Rows < max(1, n): a.Rows=1, n=2")
		_, _, err = golapack.Zheevr2stage('N', 'A', Upper, 2, a.Off(0, 0).UpdateRows(1), 0.0, 0.0, 1, 1, 0.0, r, z.Off(0, 0).UpdateRows(1), &iw, q.Off(0, 0).CVector(), 2*n, rw, 24*n, toSlice(&iw, 2*n), 10*n)
		chkxer2("Zheevr2stage", err)
		*errt = fmt.Errorf("n > 0 && vu <= vl: n=1, vl=0, vu=0")
		_, _, err = golapack.Zheevr2stage('N', 'V', Upper, 1, a.Off(0, 0).UpdateRows(1), 0.0, 0.0, 1, 1, 0.0, r, z.Off(0, 0).UpdateRows(1), &iw, q.Off(0, 0).CVector(), 2*n, rw, 24*n, toSlice(&iw, 2*n), 10*n)
		chkxer2("Zheevr2stage", err)
		*errt = fmt.Errorf("il < 1 || il > max(1, n): n=1, il=0")
		_, _, err = golapack.Zheevr2stage('N', 'I', Upper, 1, a.Off(0, 0).UpdateRows(1), 0.0, 0.0, 0, 1, 0.0, r, z.Off(0, 0).UpdateRows(1), &iw, q.Off(0, 0).CVector(), 2*n, rw, 24*n, toSlice(&iw, 2*n), 10*n)
		chkxer2("Zheevr2stage", err)
		*errt = fmt.Errorf("iu < min(n, il) || iu > n: n=2, il=2, iu=1")
		_, _, err = golapack.Zheevr2stage('N', 'I', Upper, 2, a.Off(0, 0).UpdateRows(2), 0.0, 0.0, 2, 1, 0.0, r, z.Off(0, 0).UpdateRows(1), &iw, q.Off(0, 0).CVector(), 2*n, rw, 24*n, toSlice(&iw, 2*n), 10*n)
		chkxer2("Zheevr2stage", err)
		*errt = fmt.Errorf("z.Rows < 1 || (wantz && z.Rows < n): jobz='N', z.Rows=-1, n=1")
		_, _, err = golapack.Zheevr2stage('N', 'I', Upper, 1, a.Off(0, 0).UpdateRows(1), 0.0, 0.0, 1, 1, 0.0, r, z.Off(0, 0).UpdateRows(-1), &iw, q.Off(0, 0).CVector(), 2*n, rw, 24*n, toSlice(&iw, 2*n), 10*n)
		chkxer2("Zheevr2stage", err)
		*errt = fmt.Errorf("lwork < lwmin && !lquery: lwork=1, lwmin=6, lquery=false")
		_, _, err = golapack.Zheevr2stage('N', 'I', Upper, 1, a.Off(0, 0).UpdateRows(1), 0.0, 0.0, 1, 1, 0.0, r, z.Off(0, 0).UpdateRows(1), &iw, q.Off(0, 0).CVector(), 2*n-1, rw, 24*n, toSlice(&iw, 2*n), 10*n)
		chkxer2("Zheevr2stage", err)
		*errt = fmt.Errorf("lrwork < lrwmin && !lquery: lrwork=23, lrwmin=24, lquery=false")
		_, _, err = golapack.Zheevr2stage('N', 'I', Upper, 1, a.Off(0, 0).UpdateRows(1), 0.0, 0.0, 1, 1, 0.0, r, z.Off(0, 0).UpdateRows(1), &iw, q.Off(0, 0).CVector(), 600*n, rw, 24*n-1, toSlice(&iw, 2*n-1-1), 10*n)
		chkxer2("Zheevr2stage", err)
		*errt = fmt.Errorf("liwork < liwmin && !lquery: liwork=9, liwmin=10, lquery=false")
		_, _, err = golapack.Zheevr2stage('N', 'I', Upper, 1, a.Off(0, 0).UpdateRows(1), 0.0, 0.0, 1, 1, 0.0, r, z.Off(0, 0).UpdateRows(1), &iw, q.Off(0, 0).CVector(), 600*n, rw, 24*n, &iw, 10*n-1)
		chkxer2("Zheevr2stage", err)
		nt = nt + 13

		//        Zhpevd
		*srnamt = "Zhpevd"
		*errt = fmt.Errorf("!(wantz || jobz == 'N'): jobz='/'")
		_, err = golapack.Zhpevd('/', Upper, 0, a.Off(0, 0).CVector(), x, z.Off(0, 0).UpdateRows(1), w, 1, rw, 1, &iw, 1)
		chkxer2("Zhpevd", err)
		*errt = fmt.Errorf("!(uplo == Lower || uplo == Upper): uplo=Unrecognized: /")
		_, err = golapack.Zhpevd('N', '/', 0, a.Off(0, 0).CVector(), x, z.Off(0, 0).UpdateRows(1), w, 1, rw, 1, &iw, 1)
		chkxer2("Zhpevd", err)
		*errt = fmt.Errorf("n < 0: n=-1")
		_, err = golapack.Zhpevd('N', Upper, -1, a.Off(0, 0).CVector(), x, z.Off(0, 0).UpdateRows(1), w, 1, rw, 1, &iw, 1)
		chkxer2("Zhpevd", err)
		*errt = fmt.Errorf("z.Rows < 1 || (wantz && z.Rows < n): jobz='V', z.Rows=1, n=2")
		_, err = golapack.Zhpevd('V', Upper, 2, a.Off(0, 0).CVector(), x, z.Off(0, 0).UpdateRows(1), w, 4, rw, 25, &iw, 12)
		chkxer2("Zhpevd", err)
		*errt = fmt.Errorf("lwork < lwmin && !lquery: lwork=0, lwmin=1, lquery=false")
		_, err = golapack.Zhpevd('N', Upper, 1, a.Off(0, 0).CVector(), x, z.Off(0, 0).UpdateRows(1), w, 0, rw, 1, &iw, 1)
		chkxer2("Zhpevd", err)
		*errt = fmt.Errorf("lwork < lwmin && !lquery: lwork=1, lwmin=2, lquery=false")
		_, err = golapack.Zhpevd('N', Upper, 2, a.Off(0, 0).CVector(), x, z.Off(0, 0).UpdateRows(2), w, 1, rw, 2, &iw, 1)
		chkxer2("Zhpevd", err)
		*errt = fmt.Errorf("lwork < lwmin && !lquery: lwork=2, lwmin=4, lquery=false")
		_, err = golapack.Zhpevd('V', Upper, 2, a.Off(0, 0).CVector(), x, z.Off(0, 0).UpdateRows(2), w, 2, rw, 25, &iw, 12)
		chkxer2("Zhpevd", err)
		*errt = fmt.Errorf("lrwork < lrwmin && !lquery: lrwork=0, lrwmin=1, lquery=false")
		_, err = golapack.Zhpevd('N', Upper, 1, a.Off(0, 0).CVector(), x, z.Off(0, 0).UpdateRows(1), w, 1, rw, 0, &iw, 1)
		chkxer2("Zhpevd", err)
		*errt = fmt.Errorf("lrwork < lrwmin && !lquery: lrwork=1, lrwmin=2, lquery=false")
		_, err = golapack.Zhpevd('N', Upper, 2, a.Off(0, 0).CVector(), x, z.Off(0, 0).UpdateRows(2), w, 2, rw, 1, &iw, 1)
		chkxer2("Zhpevd", err)
		*errt = fmt.Errorf("lrwork < lrwmin && !lquery: lrwork=18, lrwmin=19, lquery=false")
		_, err = golapack.Zhpevd('V', Upper, 2, a.Off(0, 0).CVector(), x, z.Off(0, 0).UpdateRows(2), w, 4, rw, 18, &iw, 12)
		chkxer2("Zhpevd", err)
		*errt = fmt.Errorf("liwork < liwmin && !lquery: liwork=0, liwmin=1, lquery=false")
		_, err = golapack.Zhpevd('N', Upper, 1, a.Off(0, 0).CVector(), x, z.Off(0, 0).UpdateRows(1), w, 1, rw, 1, &iw, 0)
		chkxer2("Zhpevd", err)
		*errt = fmt.Errorf("liwork < liwmin && !lquery: liwork=0, liwmin=1, lquery=false")
		_, err = golapack.Zhpevd('N', Upper, 2, a.Off(0, 0).CVector(), x, z.Off(0, 0).UpdateRows(2), w, 2, rw, 2, &iw, 0)
		chkxer2("Zhpevd", err)
		*errt = fmt.Errorf("liwork < liwmin && !lquery: liwork=2, liwmin=13, lquery=false")
		_, err = golapack.Zhpevd('V', Upper, 2, a.Off(0, 0).CVector(), x, z.Off(0, 0).UpdateRows(2), w, 4, rw, 25, &iw, 2)
		chkxer2("Zhpevd", err)
		nt = nt + 13

		//        ZHPEV
		*srnamt = "Zhpev"
		*errt = fmt.Errorf("!(wantz || jobz == 'N'): jobz='/'")
		_, err = golapack.Zhpev('/', Upper, 0, a.Off(0, 0).CVector(), x, z.Off(0, 0).UpdateRows(1), w, rw)
		chkxer2("Zhpev", err)
		*errt = fmt.Errorf("!(uplo == Lower || uplo == Upper): uplo=Unrecognized: /")
		_, err = golapack.Zhpev('N', '/', 0, a.Off(0, 0).CVector(), x, z.Off(0, 0).UpdateRows(1), w, rw)
		chkxer2("Zhpev", err)
		*errt = fmt.Errorf("n < 0: n=-1")
		_, err = golapack.Zhpev('N', Upper, -1, a.Off(0, 0).CVector(), x, z.Off(0, 0).UpdateRows(1), w, rw)
		chkxer2("Zhpev", err)
		*errt = fmt.Errorf("z.Rows < 1 || (wantz && z.Rows < n): jobz='V', z.Rows=1, n=2")
		_, err = golapack.Zhpev('V', Upper, 2, a.Off(0, 0).CVector(), x, z.Off(0, 0).UpdateRows(1), w, rw)
		chkxer2("Zhpev", err)
		nt = nt + 4

		//        Zhpevx
		*srnamt = "Zhpevx"
		*errt = fmt.Errorf("!(wantz || jobz == 'N'): jobz='/'")
		_, _, err = golapack.Zhpevx('/', 'A', Upper, 0, a.Off(0, 0).CVector(), 0.0, 0.0, 0, 0, 0.0, x, z.Off(0, 0).UpdateRows(1), w, rw, &iw, &i3)
		chkxer2("Zhpevx", err)
		*errt = fmt.Errorf("!(alleig || valeig || indeig): _range='/'")
		_, _, err = golapack.Zhpevx('V', '/', Upper, 0, a.Off(0, 0).CVector(), 0.0, 1.0, 1, 0, 0.0, x, z.Off(0, 0).UpdateRows(1), w, rw, &iw, &i3)
		chkxer2("Zhpevx", err)
		*errt = fmt.Errorf("!(uplo == Lower || uplo == Upper): uplo=Unrecognized: /")
		_, _, err = golapack.Zhpevx('V', 'A', '/', 0, a.Off(0, 0).CVector(), 0.0, 0.0, 0, 0, 0.0, x, z.Off(0, 0).UpdateRows(1), w, rw, &iw, &i3)
		chkxer2("Zhpevx", err)
		*errt = fmt.Errorf("n < 0: n=-1")
		_, _, err = golapack.Zhpevx('V', 'A', Upper, -1, a.Off(0, 0).CVector(), 0.0, 0.0, 0, 0, 0.0, x, z.Off(0, 0).UpdateRows(1), w, rw, &iw, &i3)
		chkxer2("Zhpevx", err)
		*errt = fmt.Errorf("n > 0 && vu <= vl: n=1, vl=0, vu=0")
		_, _, err = golapack.Zhpevx('V', 'V', Upper, 1, a.Off(0, 0).CVector(), 0.0, 0.0, 0, 0, 0.0, x, z.Off(0, 0).UpdateRows(1), w, rw, &iw, &i3)
		chkxer2("Zhpevx", err)
		*errt = fmt.Errorf("il < 1 || il > max(1, n): n=1, il=0")
		_, _, err = golapack.Zhpevx('V', 'I', Upper, 1, a.Off(0, 0).CVector(), 0.0, 0.0, 0, 0, 0.0, x, z.Off(0, 0).UpdateRows(1), w, rw, &iw, &i3)
		chkxer2("Zhpevx", err)
		*errt = fmt.Errorf("iu < min(n, il) || iu > n: n=2, il=2, iu=1")
		_, _, err = golapack.Zhpevx('V', 'I', Upper, 2, a.Off(0, 0).CVector(), 0.0, 0.0, 2, 1, 0.0, x, z.Off(0, 0).UpdateRows(2), w, rw, &iw, &i3)
		chkxer2("Zhpevx", err)
		*errt = fmt.Errorf("z.Rows < 1 || (wantz && z.Rows < n): jobz='V', z.Rows=1, n=2")
		_, _, err = golapack.Zhpevx('V', 'A', Upper, 2, a.Off(0, 0).CVector(), 0.0, 0.0, 0, 0, 0.0, x, z.Off(0, 0).UpdateRows(1), w, rw, &iw, &i3)
		chkxer2("Zhpevx", err)
		nt = nt + 8

		//     Test error exits for the hb path.
	} else if c2 == "hb" {
		//        Zhbtrd
		*srnamt = "Zhbtrd"
		*errt = fmt.Errorf("!wantq && vect != 'N': vect='/'")
		err = golapack.Zhbtrd('/', Upper, 0, 0, a.Off(0, 0).UpdateRows(1), d, e, z.Off(0, 0).UpdateRows(1), w)
		chkxer2("Zhbtrd", err)
		*errt = fmt.Errorf("!upper && uplo != Lower: uplo=Unrecognized: /")
		err = golapack.Zhbtrd('N', '/', 0, 0, a.Off(0, 0).UpdateRows(1), d, e, z.Off(0, 0).UpdateRows(1), w)
		chkxer2("Zhbtrd", err)
		*errt = fmt.Errorf("n < 0: n=-1")
		err = golapack.Zhbtrd('N', Upper, -1, 0, a.Off(0, 0).UpdateRows(1), d, e, z.Off(0, 0).UpdateRows(1), w)
		chkxer2("Zhbtrd", err)
		*errt = fmt.Errorf("kd < 0: kd=-1")
		err = golapack.Zhbtrd('N', Upper, 0, -1, a.Off(0, 0).UpdateRows(1), d, e, z.Off(0, 0).UpdateRows(1), w)
		chkxer2("Zhbtrd", err)
		*errt = fmt.Errorf("ab.Rows < kd1: ab.Rows=1, kd1=2")
		err = golapack.Zhbtrd('N', Upper, 1, 1, a.Off(0, 0).UpdateRows(1), d, e, z.Off(0, 0).UpdateRows(1), w)
		chkxer2("Zhbtrd", err)
		*errt = fmt.Errorf("q.Rows < max(1, n) && wantq: vect='V', q.Rows=1, n=2")
		err = golapack.Zhbtrd('V', Upper, 2, 0, a.Off(0, 0).UpdateRows(1), d, e, z.Off(0, 0).UpdateRows(1), w)
		chkxer2("Zhbtrd", err)
		nt = nt + 6

		//        ZhetrdHb2st
		*srnamt = "ZhetrdHb2st"
		*errt = fmt.Errorf("!afters1 && stage1 != 'N': stage1='/'")
		err = golapack.ZhetrdHb2st('/', 'N', Upper, 0, 0, a.Off(0, 0).UpdateRows(1), d, e, c.Off(0, 0).CVector(), 1, w, 1)
		chkxer2("ZhetrdHb2st", err)
		*errt = fmt.Errorf("vect != 'N': vect='/'")
		err = golapack.ZhetrdHb2st('N', '/', Upper, 0, 0, a.Off(0, 0).UpdateRows(1), d, e, c.Off(0, 0).CVector(), 1, w, 1)
		chkxer2("ZhetrdHb2st", err)
		*errt = fmt.Errorf("vect != 'N': vect='H'")
		err = golapack.ZhetrdHb2st('N', 'H', Upper, 0, 0, a.Off(0, 0).UpdateRows(1), d, e, c.Off(0, 0).CVector(), 1, w, 1)
		chkxer2("ZhetrdHb2st", err)
		*errt = fmt.Errorf("!upper && uplo != Lower: uplo=Unrecognized: /")
		err = golapack.ZhetrdHb2st('N', 'N', '/', 0, 0, a.Off(0, 0).UpdateRows(1), d, e, c.Off(0, 0).CVector(), 1, w, 1)
		chkxer2("ZhetrdHb2st", err)
		*errt = fmt.Errorf("n < 0: n=-1")
		err = golapack.ZhetrdHb2st('N', 'N', Upper, -1, 0, a.Off(0, 0).UpdateRows(1), d, e, c.Off(0, 0).CVector(), 1, w, 1)
		chkxer2("ZhetrdHb2st", err)
		*errt = fmt.Errorf("kd < 0: kd=-1")
		err = golapack.ZhetrdHb2st('N', 'N', Upper, 0, -1, a.Off(0, 0).UpdateRows(1), d, e, c.Off(0, 0).CVector(), 1, w, 1)
		chkxer2("ZhetrdHb2st", err)
		*errt = fmt.Errorf("ab.Rows < (kd + 1): ab.Rows=1, kd=1")
		err = golapack.ZhetrdHb2st('N', 'N', Upper, 0, 1, a.Off(0, 0).UpdateRows(1), d, e, c.Off(0, 0).CVector(), 1, w, 1)
		chkxer2("ZhetrdHb2st", err)
		*errt = fmt.Errorf("lhous < lhmin && !lquery: lhous=0, lhmin=1, lquery=false")
		err = golapack.ZhetrdHb2st('N', 'N', Upper, 0, 0, a.Off(0, 0).UpdateRows(1), d, e, c.Off(0, 0).CVector(), 0, w, 1)
		chkxer2("ZhetrdHb2st", err)
		*errt = fmt.Errorf("lwork < lwmin && !lquery: lwork=0, lwmin=1, lquery=false")
		err = golapack.ZhetrdHb2st('N', 'N', Upper, 0, 0, a.Off(0, 0).UpdateRows(1), d, e, c.Off(0, 0).CVector(), 1, w, 0)
		chkxer2("ZhetrdHb2st", err)
		nt = nt + 9

		//        Zhbevd
		*srnamt = "Zhbevd"
		*errt = fmt.Errorf("!(wantz || jobz == 'N'): jobz='/'")
		_, err = golapack.Zhbevd('/', Upper, 0, 0, a.Off(0, 0).UpdateRows(1), x, z.Off(0, 0).UpdateRows(1), w, 1, rw, 1, &iw, 1)
		chkxer2("Zhbevd", err)
		*errt = fmt.Errorf("!(lower || uplo == Upper): uplo=Unrecognized: /")
		_, err = golapack.Zhbevd('N', '/', 0, 0, a.Off(0, 0).UpdateRows(1), x, z.Off(0, 0).UpdateRows(1), w, 1, rw, 1, &iw, 1)
		chkxer2("Zhbevd", err)
		*errt = fmt.Errorf("n < 0: n=-1")
		_, err = golapack.Zhbevd('N', Upper, -1, 0, a.Off(0, 0).UpdateRows(1), x, z.Off(0, 0).UpdateRows(1), w, 1, rw, 1, &iw, 1)
		chkxer2("Zhbevd", err)
		*errt = fmt.Errorf("kd < 0: kd=-1")
		_, err = golapack.Zhbevd('N', Upper, 0, -1, a.Off(0, 0).UpdateRows(1), x, z.Off(0, 0).UpdateRows(1), w, 1, rw, 1, &iw, 1)
		chkxer2("Zhbevd", err)
		*errt = fmt.Errorf("ab.Rows < kd+1: ab.Rows=1, kd=1")
		_, err = golapack.Zhbevd('N', Upper, 2, 1, a.Off(0, 0).UpdateRows(1), x, z.Off(0, 0).UpdateRows(1), w, 2, rw, 2, &iw, 1)
		chkxer2("Zhbevd", err)
		*errt = fmt.Errorf("z.Rows < 1 || (wantz && z.Rows < n): jobz='V', z.Rows=1, n=2")
		_, err = golapack.Zhbevd('V', Upper, 2, 1, a.Off(0, 0).UpdateRows(2), x, z.Off(0, 0).UpdateRows(1), w, 8, rw, 25, &iw, 12)
		chkxer2("Zhbevd", err)
		*errt = fmt.Errorf("lwork < lwmin && !lquery: lwork=0, lwmin=1, lquery=false")
		_, err = golapack.Zhbevd('N', Upper, 1, 0, a.Off(0, 0).UpdateRows(1), x, z.Off(0, 0).UpdateRows(1), w, 0, rw, 1, &iw, 1)
		chkxer2("Zhbevd", err)
		*errt = fmt.Errorf("lwork < lwmin && !lquery: lwork=1, lwmin=2, lquery=false")
		_, err = golapack.Zhbevd('N', Upper, 2, 1, a.Off(0, 0).UpdateRows(2), x, z.Off(0, 0).UpdateRows(2), w, 1, rw, 2, &iw, 1)
		chkxer2("Zhbevd", err)
		*errt = fmt.Errorf("lwork < lwmin && !lquery: lwork=2, lwmin=8, lquery=false")
		_, err = golapack.Zhbevd('V', Upper, 2, 1, a.Off(0, 0).UpdateRows(2), x, z.Off(0, 0).UpdateRows(2), w, 2, rw, 25, &iw, 12)
		chkxer2("Zhbevd", err)
		*errt = fmt.Errorf("lrwork < lrwmin && !lquery: lrwork=0, lrwmin=1, lquery=false")
		_, err = golapack.Zhbevd('N', Upper, 1, 0, a.Off(0, 0).UpdateRows(1), x, z.Off(0, 0).UpdateRows(1), w, 1, rw, 0, &iw, 1)
		chkxer2("Zhbevd", err)
		*errt = fmt.Errorf("lrwork < lrwmin && !lquery: lrwork=1, lrwmin=2, lquery=false")
		_, err = golapack.Zhbevd('N', Upper, 2, 1, a.Off(0, 0).UpdateRows(2), x, z.Off(0, 0).UpdateRows(2), w, 2, rw, 1, &iw, 1)
		chkxer2("Zhbevd", err)
		*errt = fmt.Errorf("lrwork < lrwmin && !lquery: lrwork=2, lrwmin=19, lquery=false")
		_, err = golapack.Zhbevd('V', Upper, 2, 1, a.Off(0, 0).UpdateRows(2), x, z.Off(0, 0).UpdateRows(2), w, 8, rw, 2, &iw, 12)
		chkxer2("Zhbevd", err)
		*errt = fmt.Errorf("liwork < liwmin && !lquery: liwork=0, liwmin=1, lquery=false")
		_, err = golapack.Zhbevd('N', Upper, 1, 0, a.Off(0, 0).UpdateRows(1), x, z.Off(0, 0).UpdateRows(1), w, 1, rw, 1, &iw, 0)
		chkxer2("Zhbevd", err)
		*errt = fmt.Errorf("liwork < liwmin && !lquery: liwork=0, liwmin=1, lquery=false")
		_, err = golapack.Zhbevd('N', Upper, 2, 1, a.Off(0, 0).UpdateRows(2), x, z.Off(0, 0).UpdateRows(2), w, 2, rw, 2, &iw, 0)
		chkxer2("Zhbevd", err)
		*errt = fmt.Errorf("liwork < liwmin && !lquery: liwork=2, liwmin=13, lquery=false")
		_, err = golapack.Zhbevd('V', Upper, 2, 1, a.Off(0, 0).UpdateRows(2), x, z.Off(0, 0).UpdateRows(2), w, 8, rw, 25, &iw, 2)
		chkxer2("Zhbevd", err)
		nt = nt + 15

		//        Zhbevd2stage
		*srnamt = "Zhbevd2stage"
		*errt = fmt.Errorf("jobz != 'N': jobz='/'")
		_, err = golapack.Zhbevd2stage('/', Upper, 0, 0, a.Off(0, 0).UpdateRows(1), x, z.Off(0, 0).UpdateRows(1), w, 1, rw, 1, &iw, 1)
		chkxer2("Zhbevd2stage", err)
		*errt = fmt.Errorf("jobz != 'N': jobz='V'")
		_, err = golapack.Zhbevd2stage('V', Upper, 0, 0, a.Off(0, 0).UpdateRows(1), x, z.Off(0, 0).UpdateRows(1), w, 1, rw, 1, &iw, 1)
		chkxer2("Zhbevd2stage", err)
		*errt = fmt.Errorf("!(lower || uplo == Upper): uplo=Unrecognized: /")
		_, err = golapack.Zhbevd2stage('N', '/', 0, 0, a.Off(0, 0).UpdateRows(1), x, z.Off(0, 0).UpdateRows(1), w, 1, rw, 1, &iw, 1)
		chkxer2("Zhbevd2stage", err)
		*errt = fmt.Errorf("n < 0: n=-1")
		_, err = golapack.Zhbevd2stage('N', Upper, -1, 0, a.Off(0, 0).UpdateRows(1), x, z.Off(0, 0).UpdateRows(1), w, 1, rw, 1, &iw, 1)
		chkxer2("Zhbevd2stage", err)
		*errt = fmt.Errorf("kd < 0: kd=-1")
		_, err = golapack.Zhbevd2stage('N', Upper, 0, -1, a.Off(0, 0).UpdateRows(1), x, z.Off(0, 0).UpdateRows(1), w, 1, rw, 1, &iw, 1)
		chkxer2("Zhbevd2stage", err)
		*errt = fmt.Errorf("ab.Rows < kd+1: ab.Rows=1, kd=1")
		_, err = golapack.Zhbevd2stage('N', Upper, 2, 1, a.Off(0, 0).UpdateRows(1), x, z.Off(0, 0).UpdateRows(1), w, 2, rw, 2, &iw, 1)
		chkxer2("Zhbevd2stage", err)
		*errt = fmt.Errorf("lwork < lwmin && !lquery: lwork=0, lwmin=1, lquery=false")
		_, err = golapack.Zhbevd2stage('N', Upper, 1, 0, a.Off(0, 0).UpdateRows(1), x, z.Off(0, 0).UpdateRows(1), w, 0, rw, 1, &iw, 1)
		chkxer2("Zhbevd2stage", err)
		*errt = fmt.Errorf("lwork < lwmin && !lquery: lwork=1, lwmin=15, lquery=false")
		_, err = golapack.Zhbevd2stage('N', Upper, 2, 1, a.Off(0, 0).UpdateRows(2), x, z.Off(0, 0).UpdateRows(2), w, 1, rw, 2, &iw, 1)
		chkxer2("Zhbevd2stage", err)
		*errt = fmt.Errorf("lrwork < lrwmin && !lquery: lrwork=0, lrwmin=1, lquery=false")
		_, err = golapack.Zhbevd2stage('N', Upper, 1, 0, a.Off(0, 0).UpdateRows(1), x, z.Off(0, 0).UpdateRows(1), w, 1, rw, 0, &iw, 1)
		chkxer2("Zhbevd2stage", err)
		*errt = fmt.Errorf("lrwork < lrwmin && !lquery: lrwork=1, lrwmin=2, lquery=false")
		_, err = golapack.Zhbevd2stage('N', Upper, 2, 1, a.Off(0, 0).UpdateRows(2), x, z.Off(0, 0).UpdateRows(2), w, 25, rw, 1, &iw, 1)
		chkxer2("Zhbevd2stage", err)
		*errt = fmt.Errorf("liwork < liwmin && !lquery: liwork=0, liwmin=1, lquery=false")
		_, err = golapack.Zhbevd2stage('N', Upper, 1, 0, a.Off(0, 0).UpdateRows(1), x, z.Off(0, 0).UpdateRows(1), w, 1, rw, 1, &iw, 0)
		chkxer2("Zhbevd2stage", err)
		*errt = fmt.Errorf("liwork < liwmin && !lquery: liwork=0, liwmin=1, lquery=false")
		_, err = golapack.Zhbevd2stage('N', Upper, 2, 1, a.Off(0, 0).UpdateRows(2), x, z.Off(0, 0).UpdateRows(2), w, 25, rw, 2, &iw, 0)
		chkxer2("Zhbevd2stage", err)
		nt = nt + 13

		//        ZHBEV
		*srnamt = "Zhbev"
		*errt = fmt.Errorf("!(wantz || jobz == 'N'): jobz='/'")
		_, err = golapack.Zhbev('/', Upper, 0, 0, a.Off(0, 0).UpdateRows(1), x, z.Off(0, 0).UpdateRows(1), w, rw)
		chkxer2("Zhbev", err)
		*errt = fmt.Errorf("!(lower || uplo == Upper): uplo=Unrecognized: /")
		_, err = golapack.Zhbev('N', '/', 0, 0, a.Off(0, 0).UpdateRows(1), x, z.Off(0, 0).UpdateRows(1), w, rw)
		chkxer2("Zhbev", err)
		*errt = fmt.Errorf("n < 0: n=-1")
		_, err = golapack.Zhbev('N', Upper, -1, 0, a.Off(0, 0).UpdateRows(1), x, z.Off(0, 0).UpdateRows(1), w, rw)
		chkxer2("Zhbev", err)
		*errt = fmt.Errorf("kd < 0: kd=-1")
		_, err = golapack.Zhbev('N', Upper, 0, -1, a.Off(0, 0).UpdateRows(1), x, z.Off(0, 0).UpdateRows(1), w, rw)
		chkxer2("Zhbev", err)
		*errt = fmt.Errorf("ab.Rows < kd+1: ab.Rows=1, kd=1")
		_, err = golapack.Zhbev('N', Upper, 2, 1, a.Off(0, 0).UpdateRows(1), x, z.Off(0, 0).UpdateRows(1), w, rw)
		chkxer2("Zhbev", err)
		*errt = fmt.Errorf("z.Rows < 1 || (wantz && z.Rows < n): jobz='V', z.Rows=1, n=2")
		_, err = golapack.Zhbev('V', Upper, 2, 0, a.Off(0, 0).UpdateRows(1), x, z.Off(0, 0).UpdateRows(1), w, rw)
		chkxer2("Zhbev", err)
		nt = nt + 6

		//        Zhbev2stage
		*srnamt = "Zhbev2stage"
		*errt = fmt.Errorf("jobz != 'N': jobz='/'")
		_, err = golapack.Zhbev2stage('/', Upper, 0, 0, a.Off(0, 0).UpdateRows(1), x, z.Off(0, 0).UpdateRows(1), w, 0, rw)
		chkxer2("Zhbev2stage", err)
		*errt = fmt.Errorf("jobz != 'N': jobz='V'")
		_, err = golapack.Zhbev2stage('V', Upper, 0, 0, a.Off(0, 0).UpdateRows(1), x, z.Off(0, 0).UpdateRows(1), w, 0, rw)
		chkxer2("Zhbev2stage", err)
		*errt = fmt.Errorf("!(lower || uplo == Upper): uplo=Unrecognized: /")
		_, err = golapack.Zhbev2stage('N', '/', 0, 0, a.Off(0, 0).UpdateRows(1), x, z.Off(0, 0).UpdateRows(1), w, 0, rw)
		chkxer2("Zhbev2stage", err)
		*errt = fmt.Errorf("n < 0: n=-1")
		_, err = golapack.Zhbev2stage('N', Upper, -1, 0, a.Off(0, 0).UpdateRows(1), x, z.Off(0, 0).UpdateRows(1), w, 0, rw)
		chkxer2("Zhbev2stage", err)
		*errt = fmt.Errorf("kd < 0: kd=-1")
		_, err = golapack.Zhbev2stage('N', Upper, 0, -1, a.Off(0, 0).UpdateRows(1), x, z.Off(0, 0).UpdateRows(1), w, 0, rw)
		chkxer2("Zhbev2stage", err)
		*errt = fmt.Errorf("ab.Rows < kd+1: ab.Rows=1, kd=1")
		_, err = golapack.Zhbev2stage('N', Upper, 2, 1, a.Off(0, 0).UpdateRows(1), x, z.Off(0, 0).UpdateRows(1), w, 0, rw)
		chkxer2("Zhbev2stage", err)
		*errt = fmt.Errorf("lwork < lwmin && !lquery: lwork=0, lwmin=10, lquery=false")
		_, err = golapack.Zhbev2stage('N', Upper, 2, 0, a.Off(0, 0).UpdateRows(1), x, z.Off(0, 0).UpdateRows(1), w, 0, rw)
		chkxer2("Zhbev2stage", err)
		nt = nt + 8

		//        Zhbevx
		*srnamt = "Zhbevx"
		*errt = fmt.Errorf("!(wantz || jobz == 'N'): jobz='/'")
		_, _, err = golapack.Zhbevx('/', 'A', Upper, 0, 0, a.Off(0, 0).UpdateRows(1), q.Off(0, 0).UpdateRows(1), 0.0, 0.0, 0, 0, 0.0, x, z.Off(0, 0).UpdateRows(1), w, rw, &iw, &i3)
		chkxer2("Zhbevx", err)
		*errt = fmt.Errorf("!(alleig || valeig || indeig): _range='/'")
		_, _, err = golapack.Zhbevx('V', '/', Upper, 0, 0, a.Off(0, 0).UpdateRows(1), q.Off(0, 0).UpdateRows(1), 0.0, 1.0, 1, 0, 0.0, x, z.Off(0, 0).UpdateRows(1), w, rw, &iw, &i3)
		chkxer2("Zhbevx", err)
		*errt = fmt.Errorf("!(lower || uplo == Upper): uplo=Unrecognized: /")
		_, _, err = golapack.Zhbevx('V', 'A', '/', 0, 0, a.Off(0, 0).UpdateRows(1), q.Off(0, 0).UpdateRows(1), 0.0, 0.0, 0, 0, 0.0, x, z.Off(0, 0).UpdateRows(1), w, rw, &iw, &i3)
		*errt = fmt.Errorf("n < 0: n=-1")
		_, _, err = golapack.Zhbevx('V', 'A', Upper, -1, 0, a.Off(0, 0).UpdateRows(1), q.Off(0, 0).UpdateRows(1), 0.0, 0.0, 0, 0, 0.0, x, z.Off(0, 0).UpdateRows(1), w, rw, &iw, &i3)
		chkxer2("Zhbevx", err)
		*errt = fmt.Errorf("kd < 0: kd=-1")
		_, _, err = golapack.Zhbevx('V', 'A', Upper, 0, -1, a.Off(0, 0).UpdateRows(1), q.Off(0, 0).UpdateRows(1), 0.0, 0.0, 0, 0, 0.0, x, z.Off(0, 0).UpdateRows(1), w, rw, &iw, &i3)
		chkxer2("Zhbevx", err)
		*errt = fmt.Errorf("ab.Rows < kd+1: ab.Rows=1, kd=1")
		_, _, err = golapack.Zhbevx('V', 'A', Upper, 2, 1, a.Off(0, 0).UpdateRows(1), q.Off(0, 0).UpdateRows(2), 0.0, 0.0, 0, 0, 0.0, x, z.Off(0, 0).UpdateRows(2), w, rw, &iw, &i3)
		chkxer2("Zhbevx", err)
		*errt = fmt.Errorf("wantz && q.Rows < max(1, n): jobz='V', q.Rows=1, n=2")
		_, _, err = golapack.Zhbevx('V', 'A', Upper, 2, 0, a.Off(0, 0).UpdateRows(1), q.Off(0, 0).UpdateRows(1), 0.0, 0.0, 0, 0, 0.0, x, z.Off(0, 0).UpdateRows(2), w, rw, &iw, &i3)
		chkxer2("Zhbevx", err)
		*errt = fmt.Errorf("n > 0 && vu <= vl: n=1, vl=0, vu=0")
		_, _, err = golapack.Zhbevx('V', 'V', Upper, 1, 0, a.Off(0, 0).UpdateRows(1), q.Off(0, 0).UpdateRows(1), 0.0, 0.0, 0, 0, 0.0, x, z.Off(0, 0).UpdateRows(1), w, rw, &iw, &i3)
		chkxer2("Zhbevx", err)
		*errt = fmt.Errorf("il < 1 || il > max(1, n); n=1, il=0")
		_, _, err = golapack.Zhbevx('V', 'I', Upper, 1, 0, a.Off(0, 0).UpdateRows(1), q.Off(0, 0).UpdateRows(1), 0.0, 0.0, 0, 0, 0.0, x, z.Off(0, 0).UpdateRows(1), w, rw, &iw, &i3)
		chkxer2("Zhbevx", err)
		*errt = fmt.Errorf("iu < min(n, il) || iu > n: n=1, il=1, iu=2")
		_, _, err = golapack.Zhbevx('V', 'I', Upper, 1, 0, a.Off(0, 0).UpdateRows(1), q.Off(0, 0).UpdateRows(1), 0.0, 0.0, 1, 2, 0.0, x, z.Off(0, 0).UpdateRows(1), w, rw, &iw, &i3)
		chkxer2("Zhbevx", err)
		*errt = fmt.Errorf("z.Rows < 1 || (wantz && z.Rows < n): jobz='V', z.Rows=1, n=2")
		_, _, err = golapack.Zhbevx('V', 'A', Upper, 2, 0, a.Off(0, 0).UpdateRows(1), q.Off(0, 0).UpdateRows(2), 0.0, 0.0, 0, 0, 0.0, x, z.Off(0, 0).UpdateRows(1), w, rw, &iw, &i3)
		chkxer2("Zhbevx", err)
		nt = nt + 11

		//        Zhbevx2stage
		*srnamt = "Zhbevx2stage"
		*errt = fmt.Errorf("jobz != 'N': jobz='/'")
		_, _, err = golapack.Zhbevx2stage('/', 'A', Upper, 0, 0, a.Off(0, 0).UpdateRows(1), q.Off(0, 0).UpdateRows(1), 0.0, 0.0, 0, 0, 0.0, x, z.Off(0, 0).UpdateRows(1), w, 0, rw, &iw, &i3)
		chkxer2("Zhbevx2stage", err)
		*errt = fmt.Errorf("jobz != 'N': jobz='V'")
		_, _, err = golapack.Zhbevx2stage('V', 'A', Upper, 0, 0, a.Off(0, 0).UpdateRows(1), q.Off(0, 0).UpdateRows(1), 0.0, 0.0, 0, 0, 0.0, x, z.Off(0, 0).UpdateRows(1), w, 0, rw, &iw, &i3)
		chkxer2("Zhbevx2stage", err)
		*errt = fmt.Errorf("!(alleig || valeig || indeig): _range='/'")
		_, _, err = golapack.Zhbevx2stage('N', '/', Upper, 0, 0, a.Off(0, 0).UpdateRows(1), q.Off(0, 0).UpdateRows(1), 0.0, 1.0, 1, 0, 0.0, x, z.Off(0, 0).UpdateRows(1), w, 0, rw, &iw, &i3)
		chkxer2("Zhbevx2stage", err)
		*errt = fmt.Errorf("!(lower || uplo == Upper): uplo=Unrecognized: /")
		_, _, err = golapack.Zhbevx2stage('N', 'A', '/', 0, 0, a.Off(0, 0).UpdateRows(1), q.Off(0, 0).UpdateRows(1), 0.0, 0.0, 0, 0, 0.0, x, z.Off(0, 0).UpdateRows(1), w, 0, rw, &iw, &i3)
		chkxer2("Zhbevx2stage", err)
		*errt = fmt.Errorf("n < 0: n=-1")
		_, _, err = golapack.Zhbevx2stage('N', 'A', Upper, -1, 0, a.Off(0, 0).UpdateRows(1), q.Off(0, 0).UpdateRows(1), 0.0, 0.0, 0, 0, 0.0, x, z.Off(0, 0).UpdateRows(1), w, 0, rw, &iw, &i3)
		chkxer2("Zhbevx2stage", err)
		*errt = fmt.Errorf("kd < 0: kd=-1")
		_, _, err = golapack.Zhbevx2stage('N', 'A', Upper, 0, -1, a.Off(0, 0).UpdateRows(1), q.Off(0, 0).UpdateRows(1), 0.0, 0.0, 0, 0, 0.0, x, z.Off(0, 0).UpdateRows(1), w, 0, rw, &iw, &i3)
		chkxer2("Zhbevx2stage", err)
		*errt = fmt.Errorf("ab.Rows < kd+1: ab.Rows=1, kd=1")
		_, _, err = golapack.Zhbevx2stage('N', 'A', Upper, 2, 1, a.Off(0, 0).UpdateRows(1), q.Off(0, 0).UpdateRows(2), 0.0, 0.0, 0, 0, 0.0, x, z.Off(0, 0).UpdateRows(2), w, 0, rw, &iw, &i3)
		chkxer2("Zhbevx2stage", err)
		// *errt = fmt.Errorf("wantz && q.Rows < max(1, n): jobz='N', q.Rows=1, n=1")
		*errt = fmt.Errorf("n > 0 && vu <= vl: n=1, vl=0, vu=0")
		_, _, err = golapack.Zhbevx2stage('N', 'V', Upper, 1, 0, a.Off(0, 0).UpdateRows(1), q.Off(0, 0).UpdateRows(1), 0.0, 0.0, 0, 0, 0.0, x, z.Off(0, 0).UpdateRows(1), w, 0, rw, &iw, &i3)
		chkxer2("Zhbevx2stage", err)
		*errt = fmt.Errorf("il < 1 || il > max(1, n): il=0, n=1")
		_, _, err = golapack.Zhbevx2stage('N', 'I', Upper, 1, 0, a.Off(0, 0).UpdateRows(1), q.Off(0, 0).UpdateRows(1), 0.0, 0.0, 0, 0, 0.0, x, z.Off(0, 0).UpdateRows(1), w, 0, rw, &iw, &i3)
		chkxer2("Zhbevx2stage", err)
		*errt = fmt.Errorf("iu < min(n, il) || iu > n: il=1, iu=2, n=1")
		_, _, err = golapack.Zhbevx2stage('N', 'I', Upper, 1, 0, a.Off(0, 0).UpdateRows(1), q.Off(0, 0).UpdateRows(1), 0.0, 0.0, 1, 2, 0.0, x, z.Off(0, 0).UpdateRows(1), w, 0, rw, &iw, &i3)
		chkxer2("Zhbevx2stage", err)
		*errt = fmt.Errorf("lwork < lwmin && !lquery: lwork=0, lwmin=10, lquery=false")
		_, _, err = golapack.Zhbevx2stage('N', 'A', Upper, 2, 0, a.Off(0, 0).UpdateRows(1), q.Off(0, 0).UpdateRows(2), 0.0, 0.0, 0, 0, 0.0, x, z.Off(0, 0).UpdateRows(1), w, 0, rw, &iw, &i3)
		chkxer2("Zhbevx2stage", err)
		nt = nt + 12
	}

	//     Print a summary line.
	// if *ok {
	// 	fmt.Printf(" error exits: Passed (%5d tests run)\n", nt)
	// } else {
	// 	fmt.Printf(" *** %3s routines failed the tests of the error exits ***\n", path)
	// }
	*infot = 0
	*srnamt = ""
	if !(*ok) {
		t.Fail()
	}

	return
}
